
package com.ejada.atmc.acl.ws.proxy.yakeen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 * 
 */
@WebService(
		name = "Yakeen4AlinmaTM",
		targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/"
)
@XmlSeeAlso(
	{ ObjectFactory.class }
)
public interface Yakeen4AlinmaTM {

	/**
	 * 
	 * @param  companyAddressInfoByCrRequest
	 * @return                                returns com.ejada.atmc.acl.ws.proxy.yakeen.CompanyAddressInfoByCrResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "CompanyAddressInfoByCrResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getCompanyAddressInfoByCr",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCompanyAddressInfoByCr"
	)
	@ResponseWrapper(
			localName = "getCompanyAddressInfoByCrResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCompanyAddressInfoByCrResponse"
	)
	public CompanyAddressInfoByCrResult getCompanyAddressInfoByCr(@WebParam(
			name = "CompanyAddressInfoByCrRequest",
			targetNamespace = ""
	)
	CompanyAddressInfoByCrRequest companyAddressInfoByCrRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  citizenCarInfoBySequenceRequest
	 * @return                                 returns com.ejada.atmc.acl.ws.proxy.yakeen.CitizenCarInfoBySequenceResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "CitizenCarInfoBySequenceResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getCitizenCarInfoBySequence",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCitizenCarInfoBySequence"
	)
	@ResponseWrapper(
			localName = "getCitizenCarInfoBySequenceResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCitizenCarInfoBySequenceResponse"
	)
	public CitizenCarInfoBySequenceResult getCitizenCarInfoBySequence(@WebParam(
			name = "CitizenCarInfoBySequenceRequest",
			targetNamespace = ""
	)
	CitizenCarInfoBySequenceRequest citizenCarInfoBySequenceRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  alienCarInfoBySequenceRequest
	 * @return                                returns com.ejada.atmc.acl.ws.proxy.yakeen.AlienCarInfoBySequenceResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "AlienCarInfoBySequenceResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getAlienCarInfoBySequence",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienCarInfoBySequence"
	)
	@ResponseWrapper(
			localName = "getAlienCarInfoBySequenceResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienCarInfoBySequenceResponse"
	)
	public AlienCarInfoBySequenceResult getAlienCarInfoBySequence(@WebParam(
			name = "AlienCarInfoBySequenceRequest",
			targetNamespace = ""
	)
	AlienCarInfoBySequenceRequest alienCarInfoBySequenceRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  alienAddressInfoRequest
	 * @return                                returns com.ejada.atmc.acl.ws.proxy.yakeen.AlienAddressInfoResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "AlienAddressInfoResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getAlienAddressInfo",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienAddressInfo"
	)
	@ResponseWrapper(
			localName = "getAlienAddressInfoResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienAddressInfoResponse"
	)
	public AlienAddressInfoResult getAlienAddressInfo(@WebParam(
			name = "AlienAddressInfoRequest",
			targetNamespace = ""
	)
	AlienAddressInfoRequest alienAddressInfoRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  alienInfoByIqamaRequest
	 * @return                                returns com.ejada.atmc.acl.ws.proxy.yakeen.AlienInfoByIqamaResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "AlienInfoByIqamaResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getAlienInfoByIqama",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienInfoByIqama"
	)
	@ResponseWrapper(
			localName = "getAlienInfoByIqamaResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienInfoByIqamaResponse"
	)
	public AlienInfoByIqamaResult getAlienInfoByIqama(@WebParam(
			name = "AlienInfoByIqamaRequest",
			targetNamespace = ""
	)
	AlienInfoByIqamaRequest alienInfoByIqamaRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  alienAllDepInfoByIqamaRequest
	 * @return                                returns com.ejada.atmc.acl.ws.proxy.yakeen.AlienAllDepInfoByIqamaResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "AlienAllDepInfoByIqamaResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getAlienAllDepInfoByIqama",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienAllDepInfoByIqama"
	)
	@ResponseWrapper(
			localName = "getAlienAllDepInfoByIqamaResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienAllDepInfoByIqamaResponse"
	)
	public AlienAllDepInfoByIqamaResult getAlienAllDepInfoByIqama(@WebParam(
			name = "AlienAllDepInfoByIqamaRequest",
			targetNamespace = ""
	)
	AlienAllDepInfoByIqamaRequest alienAllDepInfoByIqamaRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  alienLegalStatusInfoRequest
	 * @return                                returns com.ejada.atmc.acl.ws.proxy.yakeen.AlienLegalStatusInfoResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "AlienLegalStatusInfoResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getAlienLegalStatusInfo",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienLegalStatusInfo"
	)
	@ResponseWrapper(
			localName = "getAlienLegalStatusInfoResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienLegalStatusInfoResponse"
	)
	public AlienLegalStatusInfoResult getAlienLegalStatusInfo(@WebParam(
			name = "AlienLegalStatusInfoRequest",
			targetNamespace = ""
	)
	AlienLegalStatusInfoRequest alienLegalStatusInfoRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  alienInfoByIqamaAndDOBRequest
	 * @return                                returns com.ejada.atmc.acl.ws.proxy.yakeen.AlienInfoByIqamaAndDOBResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "AlienInfoByIqamaAndDOBResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getAlienInfoByIqamaAndDOB",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienInfoByIqamaAndDOB"
	)
	@ResponseWrapper(
			localName = "getAlienInfoByIqamaAndDOBResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienInfoByIqamaAndDOBResponse"
	)
	public AlienInfoByIqamaAndDOBResult getAlienInfoByIqamaAndDOB(@WebParam(
			name = "AlienInfoByIqamaAndDOBRequest",
			targetNamespace = ""
	)
	AlienInfoByIqamaAndDOBRequest alienInfoByIqamaAndDOBRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  companyCarInfoBySequenceRequest
	 * @return                                 returns com.ejada.atmc.acl.ws.proxy.yakeen.CompanyCarInfoBySequenceResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "CompanyCarInfoBySequenceResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getCompanyCarInfoBySequence",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCompanyCarInfoBySequence"
	)
	@ResponseWrapper(
			localName = "getCompanyCarInfoBySequenceResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCompanyCarInfoBySequenceResponse"
	)
	public CompanyCarInfoBySequenceResult getCompanyCarInfoBySequence(@WebParam(
			name = "CompanyCarInfoBySequenceRequest",
			targetNamespace = ""
	)
	CompanyCarInfoBySequenceRequest companyCarInfoBySequenceRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  alienInfoByBorderNumberRequest
	 * @return                                returns com.ejada.atmc.acl.ws.proxy.yakeen.AlienInfoByBorderNumberResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "AlienInfoByBorderNumberResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getAlienInfoByBorderNumber",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienInfoByBorderNumber"
	)
	@ResponseWrapper(
			localName = "getAlienInfoByBorderNumberResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienInfoByBorderNumberResponse"
	)
	public AlienInfoByBorderNumberResult getAlienInfoByBorderNumber(@WebParam(
			name = "AlienInfoByBorderNumberRequest",
			targetNamespace = ""
	)
	AlienInfoByBorderNumberRequest alienInfoByBorderNumberRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  alienSingleDepInfoByIqamaRequest
	 * @return                                  returns com.ejada.atmc.acl.ws.proxy.yakeen.AlienSingleDepInfoByIqamaResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "AlienSingleDepInfoByIqamaResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getAlienSingleDepInfoByIqama",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienSingleDepInfoByIqama"
	)
	@ResponseWrapper(
			localName = "getAlienSingleDepInfoByIqamaResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetAlienSingleDepInfoByIqamaResponse"
	)
	public AlienSingleDepInfoByIqamaResult getAlienSingleDepInfoByIqama(@WebParam(
			name = "AlienSingleDepInfoByIqamaRequest",
			targetNamespace = ""
	)
	AlienSingleDepInfoByIqamaRequest alienSingleDepInfoByIqamaRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  carInfoByCustomRequest
	 * @return                                returns com.ejada.atmc.acl.ws.proxy.yakeen.CarInfoByCustomResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "CarInfoByCustomResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getCarInfoByCustom",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCarInfoByCustom"
	)
	@ResponseWrapper(
			localName = "getCarInfoByCustomResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCarInfoByCustomResponse"
	)
	public CarInfoByCustomResult getCarInfoByCustom(@WebParam(
			name = "CarInfoByCustomRequest",
			targetNamespace = ""
	)
	CarInfoByCustomRequest carInfoByCustomRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  citizenAddressInfoRequest
	 * @return                                returns com.ejada.atmc.acl.ws.proxy.yakeen.CitizenAddressInfoResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "CitizenAddressInfoResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getCitizenAddressInfo",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCitizenAddressInfo"
	)
	@ResponseWrapper(
			localName = "getCitizenAddressInfoResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCitizenAddressInfoResponse"
	)
	public CitizenAddressInfoResult getCitizenAddressInfo(@WebParam(
			name = "CitizenAddressInfoRequest",
			targetNamespace = ""
	)
	CitizenAddressInfoRequest citizenAddressInfoRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  citizenInfoRequest
	 * @return                                returns com.ejada.atmc.acl.ws.proxy.yakeen.CitizenInfoResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "CitizenInfoResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getCitizenInfo",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCitizenInfo"
	)
	@ResponseWrapper(
			localName = "getCitizenInfoResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCitizenInfoResponse"
	)
	public CitizenInfoResult getCitizenInfo(@WebParam(
			name = "CitizenInfoRequest",
			targetNamespace = ""
	)
	CitizenInfoRequest citizenInfoRequest) throws Yakeen4AlinmaTMFault_Exception;

	/**
	 * 
	 * @param  companyInfoBySponseredIqamaRequest
	 * @return                                    returns
	 *                                            com.ejada.atmc.acl.ws.proxy.yakeen.CompanyInfoBySponseredIqamaResult
	 * @throws Yakeen4AlinmaTMFault_Exception
	 */
	@WebMethod
	@WebResult(
			name = "CompanyInfoBySponseredIqamaResult",
			targetNamespace = ""
	)
	@RequestWrapper(
			localName = "getCompanyInfoBySponseredIqama",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCompanyInfoBySponseredIqama"
	)
	@ResponseWrapper(
			localName = "getCompanyInfoBySponseredIqamaResponse",
			targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/",
			className = "com.ejada.atmc.acl.ws.proxy.yakeen.GetCompanyInfoBySponseredIqamaResponse"
	)
	public CompanyInfoBySponseredIqamaResult getCompanyInfoBySponseredIqama(@WebParam(
			name = "CompanyInfoBySponseredIqamaRequest",
			targetNamespace = ""
	)
	CompanyInfoBySponseredIqamaRequest companyInfoBySponseredIqamaRequest) throws Yakeen4AlinmaTMFault_Exception;

}
