
package com.atmc.mob.acl.ws.proxy.najm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NCDService", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://portalservices1.najm.sa/NCDService/NCDService.svc?wsdl")
public class NCDService
    extends Service
{

    private final static URL NCDSERVICE_WSDL_LOCATION;
    private final static WebServiceException NCDSERVICE_EXCEPTION;
    private final static QName NCDSERVICE_QNAME = new QName("http://tempuri.org/", "NCDService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://portalservices1.najm.sa/NCDService/NCDService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NCDSERVICE_WSDL_LOCATION = url;
        NCDSERVICE_EXCEPTION = e;
    }

    public NCDService() {
        super(__getWsdlLocation(), NCDSERVICE_QNAME);
    }

    public NCDService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NCDSERVICE_QNAME, features);
    }

    public NCDService(URL wsdlLocation) {
        super(wsdlLocation, NCDSERVICE_QNAME);
    }

    public NCDService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NCDSERVICE_QNAME, features);
    }

    public NCDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NCDService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns INCDService
     */
    @WebEndpoint(name = "WSHttpBinding_INCDService")
    public INCDService getWSHttpBindingINCDService() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_INCDService"), INCDService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns INCDService
     */
    @WebEndpoint(name = "WSHttpBinding_INCDService")
    public INCDService getWSHttpBindingINCDService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_INCDService"), INCDService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NCDSERVICE_EXCEPTION!= null) {
            throw NCDSERVICE_EXCEPTION;
        }
        return NCDSERVICE_WSDL_LOCATION;
    }

}
