/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.sql.Blob;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ClaimAdminUploads service. Represents a row in the &quot;EJD_CLM_ADMIN_UPLOADS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.atmc.acl.db.model.impl.ClaimAdminUploadsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.atmc.acl.db.model.impl.ClaimAdminUploadsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClaimAdminUploads
 * @generated
 */
@ProviderType
public interface ClaimAdminUploadsModel extends BaseModel<ClaimAdminUploads> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a claim admin uploads model instance should use the {@link ClaimAdminUploads} interface instead.
	 */

	/**
	 * Returns the primary key of this claim admin uploads.
	 *
	 * @return the primary key of this claim admin uploads
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this claim admin uploads.
	 *
	 * @param primaryKey the primary key of this claim admin uploads
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this claim admin uploads.
	 *
	 * @return the ID of this claim admin uploads
	 */
	public int getId();

	/**
	 * Sets the ID of this claim admin uploads.
	 *
	 * @param id the ID of this claim admin uploads
	 */
	public void setId(int id);

	/**
	 * Returns the ref no of this claim admin uploads.
	 *
	 * @return the ref no of this claim admin uploads
	 */
	@AutoEscape
	public String getRefNo();

	/**
	 * Sets the ref no of this claim admin uploads.
	 *
	 * @param refNo the ref no of this claim admin uploads
	 */
	public void setRefNo(String refNo);

	/**
	 * Returns the file name of this claim admin uploads.
	 *
	 * @return the file name of this claim admin uploads
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this claim admin uploads.
	 *
	 * @param fileName the file name of this claim admin uploads
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the admin file of this claim admin uploads.
	 *
	 * @return the admin file of this claim admin uploads
	 */
	public Blob getAdminFile();

	/**
	 * Sets the admin file of this claim admin uploads.
	 *
	 * @param adminFile the admin file of this claim admin uploads
	 */
	public void setAdminFile(Blob adminFile);

}