/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CodeMaster service. Represents a row in the &quot;PM_CODE_MASTER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.atmc.acl.db.model.impl.CodeMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.atmc.acl.db.model.impl.CodeMasterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CodeMaster
 * @generated
 */
@ProviderType
public interface CodeMasterModel extends BaseModel<CodeMaster> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a code master model instance should use the {@link CodeMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this code master.
	 *
	 * @return the primary key of this code master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this code master.
	 *
	 * @param primaryKey the primary key of this code master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the system ID of this code master.
	 *
	 * @return the system ID of this code master
	 */
	public long getSystemId();

	/**
	 * Sets the system ID of this code master.
	 *
	 * @param systemId the system ID of this code master
	 */
	public void setSystemId(long systemId);

	/**
	 * Returns the eff from date of this code master.
	 *
	 * @return the eff from date of this code master
	 */
	public Date getEffFromDate();

	/**
	 * Sets the eff from date of this code master.
	 *
	 * @param effFromDate the eff from date of this code master
	 */
	public void setEffFromDate(Date effFromDate);

	/**
	 * Returns the eff to date of this code master.
	 *
	 * @return the eff to date of this code master
	 */
	public Date getEffToDate();

	/**
	 * Sets the eff to date of this code master.
	 *
	 * @param effToDate the eff to date of this code master
	 */
	public void setEffToDate(Date effToDate);

	/**
	 * Returns the creation date of this code master.
	 *
	 * @return the creation date of this code master
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this code master.
	 *
	 * @param creationDate the creation date of this code master
	 */
	public void setCreationDate(Date creationDate);

	/**
	 * Returns the cr uid of this code master.
	 *
	 * @return the cr uid of this code master
	 */
	@AutoEscape
	public String getCrUid();

	/**
	 * Sets the cr uid of this code master.
	 *
	 * @param crUid the cr uid of this code master
	 */
	public void setCrUid(String crUid);

	/**
	 * Returns the update date of this code master.
	 *
	 * @return the update date of this code master
	 */
	@AutoEscape
	public String getUpdateDate();

	/**
	 * Sets the update date of this code master.
	 *
	 * @param updateDate the update date of this code master
	 */
	public void setUpdateDate(String updateDate);

	/**
	 * Returns the update uid of this code master.
	 *
	 * @return the update uid of this code master
	 */
	public long getUpdateUid();

	/**
	 * Sets the update uid of this code master.
	 *
	 * @param updateUid the update uid of this code master
	 */
	public void setUpdateUid(long updateUid);

	/**
	 * Returns the code of this code master.
	 *
	 * @return the code of this code master
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this code master.
	 *
	 * @param code the code of this code master
	 */
	public void setCode(String code);

	/**
	 * Returns the code sub of this code master.
	 *
	 * @return the code sub of this code master
	 */
	@AutoEscape
	public String getCodeSub();

	/**
	 * Sets the code sub of this code master.
	 *
	 * @param codeSub the code sub of this code master
	 */
	public void setCodeSub(String codeSub);

	/**
	 * Returns the code desc of this code master.
	 *
	 * @return the code desc of this code master
	 */
	@AutoEscape
	public String getCodeDesc();

	/**
	 * Sets the code desc of this code master.
	 *
	 * @param codeDesc the code desc of this code master
	 */
	public void setCodeDesc(String codeDesc);

	/**
	 * Returns the code desc ar of this code master.
	 *
	 * @return the code desc ar of this code master
	 */
	@AutoEscape
	public String getCodeDescAr();

	/**
	 * Sets the code desc ar of this code master.
	 *
	 * @param codeDescAr the code desc ar of this code master
	 */
	public void setCodeDescAr(String codeDescAr);

	/**
	 * Returns the code value0 of this code master.
	 *
	 * @return the code value0 of this code master
	 */
	@AutoEscape
	public String getCodeValue0();

	/**
	 * Sets the code value0 of this code master.
	 *
	 * @param codeValue0 the code value0 of this code master
	 */
	public void setCodeValue0(String codeValue0);

	/**
	 * Returns the code value1 of this code master.
	 *
	 * @return the code value1 of this code master
	 */
	@AutoEscape
	public String getCodeValue1();

	/**
	 * Sets the code value1 of this code master.
	 *
	 * @param codeValue1 the code value1 of this code master
	 */
	public void setCodeValue1(String codeValue1);

	/**
	 * Returns the code value2 of this code master.
	 *
	 * @return the code value2 of this code master
	 */
	@AutoEscape
	public String getCodeValue2();

	/**
	 * Sets the code value2 of this code master.
	 *
	 * @param codeValue2 the code value2 of this code master
	 */
	public void setCodeValue2(String codeValue2);

	/**
	 * Returns the code ref of this code master.
	 *
	 * @return the code ref of this code master
	 */
	@AutoEscape
	public String getCodeRef();

	/**
	 * Sets the code ref of this code master.
	 *
	 * @param codeRef the code ref of this code master
	 */
	public void setCodeRef(String codeRef);

	/**
	 * Returns the code sub ref of this code master.
	 *
	 * @return the code sub ref of this code master
	 */
	@AutoEscape
	public String getCodeSubRef();

	/**
	 * Sets the code sub ref of this code master.
	 *
	 * @param codeSubRef the code sub ref of this code master
	 */
	public void setCodeSubRef(String codeSubRef);

	/**
	 * Returns the code freez yn of this code master.
	 *
	 * @return the code freez yn of this code master
	 */
	@AutoEscape
	public String getCodeFreezYN();

	/**
	 * Sets the code freez yn of this code master.
	 *
	 * @param codeFreezYN the code freez yn of this code master
	 */
	public void setCodeFreezYN(String codeFreezYN);

}