/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model;

import com.ejada.atmc.acl.db.service.persistence.ProductCoversPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductCovers service. Represents a row in the &quot;MDM_PRODUCT_COVERS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.atmc.acl.db.model.impl.ProductCoversModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.atmc.acl.db.model.impl.ProductCoversImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductCovers
 * @generated
 */
@ProviderType
public interface ProductCoversModel extends BaseModel<ProductCovers> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product covers model instance should use the {@link ProductCovers} interface instead.
	 */

	/**
	 * Returns the primary key of this product covers.
	 *
	 * @return the primary key of this product covers
	 */
	public ProductCoversPK getPrimaryKey();

	/**
	 * Sets the primary key of this product covers.
	 *
	 * @param primaryKey the primary key of this product covers
	 */
	public void setPrimaryKey(ProductCoversPK primaryKey);

	/**
	 * Returns the product code of this product covers.
	 *
	 * @return the product code of this product covers
	 */
	public long getProductCode();

	/**
	 * Sets the product code of this product covers.
	 *
	 * @param productCode the product code of this product covers
	 */
	public void setProductCode(long productCode);

	/**
	 * Returns the section code of this product covers.
	 *
	 * @return the section code of this product covers
	 */
	public long getSectionCode();

	/**
	 * Sets the section code of this product covers.
	 *
	 * @param sectionCode the section code of this product covers
	 */
	public void setSectionCode(long sectionCode);

	/**
	 * Returns the cover code of this product covers.
	 *
	 * @return the cover code of this product covers
	 */
	@AutoEscape
	public String getCoverCode();

	/**
	 * Sets the cover code of this product covers.
	 *
	 * @param coverCode the cover code of this product covers
	 */
	public void setCoverCode(String coverCode);

	/**
	 * Returns the cover name of this product covers.
	 *
	 * @return the cover name of this product covers
	 */
	@AutoEscape
	public String getCoverName();

	/**
	 * Sets the cover name of this product covers.
	 *
	 * @param coverName the cover name of this product covers
	 */
	public void setCoverName(String coverName);

	/**
	 * Returns the cover name ar of this product covers.
	 *
	 * @return the cover name ar of this product covers
	 */
	@AutoEscape
	public String getCoverNameAr();

	/**
	 * Sets the cover name ar of this product covers.
	 *
	 * @param coverNameAr the cover name ar of this product covers
	 */
	public void setCoverNameAr(String coverNameAr);

	/**
	 * Returns the cover desc of this product covers.
	 *
	 * @return the cover desc of this product covers
	 */
	@AutoEscape
	public String getCoverDesc();

	/**
	 * Sets the cover desc of this product covers.
	 *
	 * @param coverDesc the cover desc of this product covers
	 */
	public void setCoverDesc(String coverDesc);

	/**
	 * Returns the cover desc ar of this product covers.
	 *
	 * @return the cover desc ar of this product covers
	 */
	@AutoEscape
	public String getCoverDescAr();

	/**
	 * Sets the cover desc ar of this product covers.
	 *
	 * @param coverDescAr the cover desc ar of this product covers
	 */
	public void setCoverDescAr(String coverDescAr);

	/**
	 * Returns the cover premium of this product covers.
	 *
	 * @return the cover premium of this product covers
	 */
	@AutoEscape
	public String getCoverPremium();

	/**
	 * Sets the cover premium of this product covers.
	 *
	 * @param coverPremium the cover premium of this product covers
	 */
	public void setCoverPremium(String coverPremium);

	/**
	 * Returns the cover fld1 of this product covers.
	 *
	 * @return the cover fld1 of this product covers
	 */
	@AutoEscape
	public String getCoverFld1();

	/**
	 * Sets the cover fld1 of this product covers.
	 *
	 * @param coverFld1 the cover fld1 of this product covers
	 */
	public void setCoverFld1(String coverFld1);

	/**
	 * Returns the cover fld2 of this product covers.
	 *
	 * @return the cover fld2 of this product covers
	 */
	@AutoEscape
	public String getCoverFld2();

	/**
	 * Sets the cover fld2 of this product covers.
	 *
	 * @param coverFld2 the cover fld2 of this product covers
	 */
	public void setCoverFld2(String coverFld2);

	/**
	 * Returns the cover fld3 of this product covers.
	 *
	 * @return the cover fld3 of this product covers
	 */
	@AutoEscape
	public String getCoverFld3();

	/**
	 * Sets the cover fld3 of this product covers.
	 *
	 * @param coverFld3 the cover fld3 of this product covers
	 */
	public void setCoverFld3(String coverFld3);

	/**
	 * Returns the cover fld4 of this product covers.
	 *
	 * @return the cover fld4 of this product covers
	 */
	@AutoEscape
	public String getCoverFld4();

	/**
	 * Sets the cover fld4 of this product covers.
	 *
	 * @param coverFld4 the cover fld4 of this product covers
	 */
	public void setCoverFld4(String coverFld4);

}