/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the QuotationsUserAddress service. Represents a row in the &quot;EJD_QUOTATIONS_USER_ADDRESS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.atmc.acl.db.model.impl.QuotationsUserAddressModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.atmc.acl.db.model.impl.QuotationsUserAddressImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuotationsUserAddress
 * @generated
 */
@ProviderType
public interface QuotationsUserAddressModel
	extends BaseModel<QuotationsUserAddress> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a quotations user address model instance should use the {@link QuotationsUserAddress} interface instead.
	 */

	/**
	 * Returns the primary key of this quotations user address.
	 *
	 * @return the primary key of this quotations user address
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this quotations user address.
	 *
	 * @param primaryKey the primary key of this quotations user address
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user address ID of this quotations user address.
	 *
	 * @return the user address ID of this quotations user address
	 */
	public long getUserAddressId();

	/**
	 * Sets the user address ID of this quotations user address.
	 *
	 * @param userAddressId the user address ID of this quotations user address
	 */
	public void setUserAddressId(long userAddressId);

	/**
	 * Returns the driver ID of this quotations user address.
	 *
	 * @return the driver ID of this quotations user address
	 */
	public long getDriverId();

	/**
	 * Sets the driver ID of this quotations user address.
	 *
	 * @param driverId the driver ID of this quotations user address
	 */
	public void setDriverId(long driverId);

	/**
	 * Returns the quotation ID of this quotations user address.
	 *
	 * @return the quotation ID of this quotations user address
	 */
	public long getQuotationId();

	/**
	 * Sets the quotation ID of this quotations user address.
	 *
	 * @param quotationId the quotation ID of this quotations user address
	 */
	public void setQuotationId(long quotationId);

	/**
	 * Returns the build no of this quotations user address.
	 *
	 * @return the build no of this quotations user address
	 */
	@AutoEscape
	public String getBuildNo();

	/**
	 * Sets the build no of this quotations user address.
	 *
	 * @param buildNo the build no of this quotations user address
	 */
	public void setBuildNo(String buildNo);

	/**
	 * Returns the zip code of this quotations user address.
	 *
	 * @return the zip code of this quotations user address
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this quotations user address.
	 *
	 * @param zipCode the zip code of this quotations user address
	 */
	public void setZipCode(String zipCode);

	/**
	 * Returns the add no of this quotations user address.
	 *
	 * @return the add no of this quotations user address
	 */
	@AutoEscape
	public String getAddNo();

	/**
	 * Sets the add no of this quotations user address.
	 *
	 * @param addNo the add no of this quotations user address
	 */
	public void setAddNo(String addNo);

	/**
	 * Returns the st name en of this quotations user address.
	 *
	 * @return the st name en of this quotations user address
	 */
	@AutoEscape
	public String getStNameEn();

	/**
	 * Sets the st name en of this quotations user address.
	 *
	 * @param stNameEn the st name en of this quotations user address
	 */
	public void setStNameEn(String stNameEn);

	/**
	 * Returns the st name ar of this quotations user address.
	 *
	 * @return the st name ar of this quotations user address
	 */
	@AutoEscape
	public String getStNameAr();

	/**
	 * Sets the st name ar of this quotations user address.
	 *
	 * @param stNameAr the st name ar of this quotations user address
	 */
	public void setStNameAr(String stNameAr);

	/**
	 * Returns the district en of this quotations user address.
	 *
	 * @return the district en of this quotations user address
	 */
	@AutoEscape
	public String getDistrictEn();

	/**
	 * Sets the district en of this quotations user address.
	 *
	 * @param districtEn the district en of this quotations user address
	 */
	public void setDistrictEn(String districtEn);

	/**
	 * Returns the district ar of this quotations user address.
	 *
	 * @return the district ar of this quotations user address
	 */
	@AutoEscape
	public String getDistrictAr();

	/**
	 * Sets the district ar of this quotations user address.
	 *
	 * @param districtAr the district ar of this quotations user address
	 */
	public void setDistrictAr(String districtAr);

	/**
	 * Returns the city en of this quotations user address.
	 *
	 * @return the city en of this quotations user address
	 */
	@AutoEscape
	public String getCityEn();

	/**
	 * Sets the city en of this quotations user address.
	 *
	 * @param cityEn the city en of this quotations user address
	 */
	public void setCityEn(String cityEn);

	/**
	 * Returns the city ar of this quotations user address.
	 *
	 * @return the city ar of this quotations user address
	 */
	@AutoEscape
	public String getCityAr();

	/**
	 * Sets the city ar of this quotations user address.
	 *
	 * @param cityAr the city ar of this quotations user address
	 */
	public void setCityAr(String cityAr);

	/**
	 * Returns the is nat address of this quotations user address.
	 *
	 * @return the is nat address of this quotations user address
	 */
	public boolean getIsNatAddress();

	/**
	 * Returns <code>true</code> if this quotations user address is is nat address.
	 *
	 * @return <code>true</code> if this quotations user address is is nat address; <code>false</code> otherwise
	 */
	public boolean isIsNatAddress();

	/**
	 * Sets whether this quotations user address is is nat address.
	 *
	 * @param isNatAddress the is nat address of this quotations user address
	 */
	public void setIsNatAddress(boolean isNatAddress);

}