/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.sql.Blob;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the QuotationSurvey service. Represents a row in the &quot;EJD_QUOTATION_SURVEY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.atmc.acl.db.model.impl.QuotationSurveyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.atmc.acl.db.model.impl.QuotationSurveyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuotationSurvey
 * @generated
 */
@ProviderType
public interface QuotationSurveyModel extends BaseModel<QuotationSurvey> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a quotation survey model instance should use the {@link QuotationSurvey} interface instead.
	 */

	/**
	 * Returns the primary key of this quotation survey.
	 *
	 * @return the primary key of this quotation survey
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this quotation survey.
	 *
	 * @param primaryKey the primary key of this quotation survey
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the survey ID of this quotation survey.
	 *
	 * @return the survey ID of this quotation survey
	 */
	public long getSurveyId();

	/**
	 * Sets the survey ID of this quotation survey.
	 *
	 * @param surveyId the survey ID of this quotation survey
	 */
	public void setSurveyId(long surveyId);

	/**
	 * Returns the quotation ID of this quotation survey.
	 *
	 * @return the quotation ID of this quotation survey
	 */
	@AutoEscape
	public String getQuotationId();

	/**
	 * Sets the quotation ID of this quotation survey.
	 *
	 * @param quotationId the quotation ID of this quotation survey
	 */
	public void setQuotationId(String quotationId);

	/**
	 * Returns the survey video file of this quotation survey.
	 *
	 * @return the survey video file of this quotation survey
	 */
	public Blob getSurveyVideoFile();

	/**
	 * Sets the survey video file of this quotation survey.
	 *
	 * @param surveyVideoFile the survey video file of this quotation survey
	 */
	public void setSurveyVideoFile(Blob surveyVideoFile);

	/**
	 * Returns the survey video file name of this quotation survey.
	 *
	 * @return the survey video file name of this quotation survey
	 */
	@AutoEscape
	public String getSurveyVideoFileName();

	/**
	 * Sets the survey video file name of this quotation survey.
	 *
	 * @param surveyVideoFileName the survey video file name of this quotation survey
	 */
	public void setSurveyVideoFileName(String surveyVideoFileName);

	/**
	 * Returns the survey date of this quotation survey.
	 *
	 * @return the survey date of this quotation survey
	 */
	public Date getSurveyDate();

	/**
	 * Sets the survey date of this quotation survey.
	 *
	 * @param surveyDate the survey date of this quotation survey
	 */
	public void setSurveyDate(Date surveyDate);

}