/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.sql.Blob;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the QuotationDrivers service. Represents a row in the &quot;EJD_ADD_DRIVERS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.atmc.acl.db.model.impl.QuotationDriversModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.atmc.acl.db.model.impl.QuotationDriversImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuotationDrivers
 * @generated
 */
@ProviderType
public interface QuotationDriversModel extends BaseModel<QuotationDrivers> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a quotation drivers model instance should use the {@link QuotationDrivers} interface instead.
	 */

	/**
	 * Returns the primary key of this quotation drivers.
	 *
	 * @return the primary key of this quotation drivers
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this quotation drivers.
	 *
	 * @param primaryKey the primary key of this quotation drivers
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the add driver ID of this quotation drivers.
	 *
	 * @return the add driver ID of this quotation drivers
	 */
	public long getAddDriverId();

	/**
	 * Sets the add driver ID of this quotation drivers.
	 *
	 * @param addDriverId the add driver ID of this quotation drivers
	 */
	public void setAddDriverId(long addDriverId);

	/**
	 * Returns the quotation ID of this quotation drivers.
	 *
	 * @return the quotation ID of this quotation drivers
	 */
	public long getQuotationId();

	/**
	 * Sets the quotation ID of this quotation drivers.
	 *
	 * @param quotationId the quotation ID of this quotation drivers
	 */
	public void setQuotationId(long quotationId);

	/**
	 * Returns the driver dob of this quotation drivers.
	 *
	 * @return the driver dob of this quotation drivers
	 */
	public Date getDriverDob();

	/**
	 * Sets the driver dob of this quotation drivers.
	 *
	 * @param driverDob the driver dob of this quotation drivers
	 */
	public void setDriverDob(Date driverDob);

	/**
	 * Returns the driver dob h of this quotation drivers.
	 *
	 * @return the driver dob h of this quotation drivers
	 */
	@AutoEscape
	public String getDriverDobH();

	/**
	 * Sets the driver dob h of this quotation drivers.
	 *
	 * @param driverDobH the driver dob h of this quotation drivers
	 */
	public void setDriverDobH(String driverDobH);

	/**
	 * Returns the driver gender of this quotation drivers.
	 *
	 * @return the driver gender of this quotation drivers
	 */
	@AutoEscape
	public String getDriverGender();

	/**
	 * Sets the driver gender of this quotation drivers.
	 *
	 * @param driverGender the driver gender of this quotation drivers
	 */
	public void setDriverGender(String driverGender);

	/**
	 * Returns the driver ID of this quotation drivers.
	 *
	 * @return the driver ID of this quotation drivers
	 */
	public long getDriverId();

	/**
	 * Sets the driver ID of this quotation drivers.
	 *
	 * @param driverId the driver ID of this quotation drivers
	 */
	public void setDriverId(long driverId);

	/**
	 * Returns the driver ID type of this quotation drivers.
	 *
	 * @return the driver ID type of this quotation drivers
	 */
	public long getDriverIdType();

	/**
	 * Sets the driver ID type of this quotation drivers.
	 *
	 * @param driverIdType the driver ID type of this quotation drivers
	 */
	public void setDriverIdType(long driverIdType);

	/**
	 * Returns the driver name of this quotation drivers.
	 *
	 * @return the driver name of this quotation drivers
	 */
	@AutoEscape
	public String getDriverName();

	/**
	 * Sets the driver name of this quotation drivers.
	 *
	 * @param driverName the driver name of this quotation drivers
	 */
	public void setDriverName(String driverName);

	/**
	 * Returns the driver nationality of this quotation drivers.
	 *
	 * @return the driver nationality of this quotation drivers
	 */
	@AutoEscape
	public String getDriverNationality();

	/**
	 * Sets the driver nationality of this quotation drivers.
	 *
	 * @param driverNationality the driver nationality of this quotation drivers
	 */
	public void setDriverNationality(String driverNationality);

	/**
	 * Returns the driver occup of this quotation drivers.
	 *
	 * @return the driver occup of this quotation drivers
	 */
	@AutoEscape
	public String getDriverOccup();

	/**
	 * Sets the driver occup of this quotation drivers.
	 *
	 * @param driverOccup the driver occup of this quotation drivers
	 */
	public void setDriverOccup(String driverOccup);

	/**
	 * Returns the is driver under21 of this quotation drivers.
	 *
	 * @return the is driver under21 of this quotation drivers
	 */
	public boolean getIsDriverUnder21();

	/**
	 * Returns <code>true</code> if this quotation drivers is is driver under21.
	 *
	 * @return <code>true</code> if this quotation drivers is is driver under21; <code>false</code> otherwise
	 */
	public boolean isIsDriverUnder21();

	/**
	 * Sets whether this quotation drivers is is driver under21.
	 *
	 * @param isDriverUnder21 the is driver under21 of this quotation drivers
	 */
	public void setIsDriverUnder21(boolean isDriverUnder21);

	/**
	 * Returns the driver edu of this quotation drivers.
	 *
	 * @return the driver edu of this quotation drivers
	 */
	@AutoEscape
	public String getDriverEdu();

	/**
	 * Sets the driver edu of this quotation drivers.
	 *
	 * @param driverEdu the driver edu of this quotation drivers
	 */
	public void setDriverEdu(String driverEdu);

	/**
	 * Returns the driver no child of this quotation drivers.
	 *
	 * @return the driver no child of this quotation drivers
	 */
	@AutoEscape
	public String getDriverNoChild();

	/**
	 * Sets the driver no child of this quotation drivers.
	 *
	 * @param driverNoChild the driver no child of this quotation drivers
	 */
	public void setDriverNoChild(String driverNoChild);

	/**
	 * Returns the driver marital status of this quotation drivers.
	 *
	 * @return the driver marital status of this quotation drivers
	 */
	@AutoEscape
	public String getDriverMaritalStatus();

	/**
	 * Sets the driver marital status of this quotation drivers.
	 *
	 * @param driverMaritalStatus the driver marital status of this quotation drivers
	 */
	public void setDriverMaritalStatus(String driverMaritalStatus);

	/**
	 * Returns the driver no fault of this quotation drivers.
	 *
	 * @return the driver no fault of this quotation drivers
	 */
	public long getDriverNOFault();

	/**
	 * Sets the driver no fault of this quotation drivers.
	 *
	 * @param driverNOFault the driver no fault of this quotation drivers
	 */
	public void setDriverNOFault(long driverNOFault);

	/**
	 * Returns the driver no claim of this quotation drivers.
	 *
	 * @return the driver no claim of this quotation drivers
	 */
	public long getDriverNOClaim();

	/**
	 * Sets the driver no claim of this quotation drivers.
	 *
	 * @param driverNOClaim the driver no claim of this quotation drivers
	 */
	public void setDriverNOClaim(long driverNOClaim);

	/**
	 * Returns the driver convictions of this quotation drivers.
	 *
	 * @return the driver convictions of this quotation drivers
	 */
	@AutoEscape
	public String getDriverConvictions();

	/**
	 * Sets the driver convictions of this quotation drivers.
	 *
	 * @param driverConvictions the driver convictions of this quotation drivers
	 */
	public void setDriverConvictions(String driverConvictions);

	/**
	 * Returns the driver med conds of this quotation drivers.
	 *
	 * @return the driver med conds of this quotation drivers
	 */
	@AutoEscape
	public String getDriverMedConds();

	/**
	 * Sets the driver med conds of this quotation drivers.
	 *
	 * @param driverMedConds the driver med conds of this quotation drivers
	 */
	public void setDriverMedConds(String driverMedConds);

	/**
	 * Returns the ncd years of this quotation drivers.
	 *
	 * @return the ncd years of this quotation drivers
	 */
	public int getNcdYears();

	/**
	 * Sets the ncd years of this quotation drivers.
	 *
	 * @param ncdYears the ncd years of this quotation drivers
	 */
	public void setNcdYears(int ncdYears);

	/**
	 * Returns the insured relation of this quotation drivers.
	 *
	 * @return the insured relation of this quotation drivers
	 */
	@AutoEscape
	public String getInsuredRelation();

	/**
	 * Sets the insured relation of this quotation drivers.
	 *
	 * @param insuredRelation the insured relation of this quotation drivers
	 */
	public void setInsuredRelation(String insuredRelation);

	/**
	 * Returns the insured relation proof of this quotation drivers.
	 *
	 * @return the insured relation proof of this quotation drivers
	 */
	public Blob getInsuredRelationProof();

	/**
	 * Sets the insured relation proof of this quotation drivers.
	 *
	 * @param insuredRelationProof the insured relation proof of this quotation drivers
	 */
	public void setInsuredRelationProof(Blob insuredRelationProof);

	/**
	 * Returns the insured relation proof file name of this quotation drivers.
	 *
	 * @return the insured relation proof file name of this quotation drivers
	 */
	@AutoEscape
	public String getInsuredRelationProofFileName();

	/**
	 * Sets the insured relation proof file name of this quotation drivers.
	 *
	 * @param insuredRelationProofFileName the insured relation proof file name of this quotation drivers
	 */
	public void setInsuredRelationProofFileName(
		String insuredRelationProofFileName);

}