/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ServiceRequestMaster service. Represents a row in the &quot;SERVICE_REQUEST_MASTER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.atmc.acl.db.model.impl.ServiceRequestMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.atmc.acl.db.model.impl.ServiceRequestMasterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ServiceRequestMaster
 * @generated
 */
@ProviderType
public interface ServiceRequestMasterModel
	extends BaseModel<ServiceRequestMaster> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service request master model instance should use the {@link ServiceRequestMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this service request master.
	 *
	 * @return the primary key of this service request master
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this service request master.
	 *
	 * @param primaryKey the primary key of this service request master
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the reference_no of this service request master.
	 *
	 * @return the reference_no of this service request master
	 */
	@AutoEscape
	public String getREFERENCE_NO();

	/**
	 * Sets the reference_no of this service request master.
	 *
	 * @param REFERENCE_NO the reference_no of this service request master
	 */
	public void setREFERENCE_NO(String REFERENCE_NO);

	/**
	 * Returns the source of this service request master.
	 *
	 * @return the source of this service request master
	 */
	@AutoEscape
	public String getSOURCE();

	/**
	 * Sets the source of this service request master.
	 *
	 * @param SOURCE the source of this service request master
	 */
	public void setSOURCE(String SOURCE);

	/**
	 * Returns the request_category of this service request master.
	 *
	 * @return the request_category of this service request master
	 */
	@AutoEscape
	public String getREQUEST_CATEGORY();

	/**
	 * Sets the request_category of this service request master.
	 *
	 * @param REQUEST_CATEGORY the request_category of this service request master
	 */
	public void setREQUEST_CATEGORY(String REQUEST_CATEGORY);

	/**
	 * Returns the request_type of this service request master.
	 *
	 * @return the request_type of this service request master
	 */
	@AutoEscape
	public String getREQUEST_TYPE();

	/**
	 * Sets the request_type of this service request master.
	 *
	 * @param REQUEST_TYPE the request_type of this service request master
	 */
	public void setREQUEST_TYPE(String REQUEST_TYPE);

	/**
	 * Returns the product_type of this service request master.
	 *
	 * @return the product_type of this service request master
	 */
	@AutoEscape
	public String getPRODUCT_TYPE();

	/**
	 * Sets the product_type of this service request master.
	 *
	 * @param PRODUCT_TYPE the product_type of this service request master
	 */
	public void setPRODUCT_TYPE(String PRODUCT_TYPE);

	/**
	 * Returns the request_message of this service request master.
	 *
	 * @return the request_message of this service request master
	 */
	@AutoEscape
	public String getREQUEST_MESSAGE();

	/**
	 * Sets the request_message of this service request master.
	 *
	 * @param REQUEST_MESSAGE the request_message of this service request master
	 */
	public void setREQUEST_MESSAGE(String REQUEST_MESSAGE);

	/**
	 * Returns the iqama_id of this service request master.
	 *
	 * @return the iqama_id of this service request master
	 */
	@AutoEscape
	public String getIQAMA_ID();

	/**
	 * Sets the iqama_id of this service request master.
	 *
	 * @param IQAMA_ID the iqama_id of this service request master
	 */
	public void setIQAMA_ID(String IQAMA_ID);

	/**
	 * Returns the email of this service request master.
	 *
	 * @return the email of this service request master
	 */
	@AutoEscape
	public String getEMAIL();

	/**
	 * Sets the email of this service request master.
	 *
	 * @param EMAIL the email of this service request master
	 */
	public void setEMAIL(String EMAIL);

	/**
	 * Returns the mobile of this service request master.
	 *
	 * @return the mobile of this service request master
	 */
	@AutoEscape
	public String getMOBILE();

	/**
	 * Sets the mobile of this service request master.
	 *
	 * @param MOBILE the mobile of this service request master
	 */
	public void setMOBILE(String MOBILE);

	/**
	 * Returns the request_status of this service request master.
	 *
	 * @return the request_status of this service request master
	 */
	@AutoEscape
	public String getREQUEST_STATUS();

	/**
	 * Sets the request_status of this service request master.
	 *
	 * @param REQUEST_STATUS the request_status of this service request master
	 */
	public void setREQUEST_STATUS(String REQUEST_STATUS);

	/**
	 * Returns the email_flag of this service request master.
	 *
	 * @return the email_flag of this service request master
	 */
	public boolean getEMAIL_FLAG();

	/**
	 * Returns <code>true</code> if this service request master is email_flag.
	 *
	 * @return <code>true</code> if this service request master is email_flag; <code>false</code> otherwise
	 */
	public boolean isEMAIL_FLAG();

	/**
	 * Sets whether this service request master is email_flag.
	 *
	 * @param EMAIL_FLAG the email_flag of this service request master
	 */
	public void setEMAIL_FLAG(boolean EMAIL_FLAG);

	/**
	 * Returns the creator_user_id of this service request master.
	 *
	 * @return the creator_user_id of this service request master
	 */
	@AutoEscape
	public String getCREATOR_USER_ID();

	/**
	 * Sets the creator_user_id of this service request master.
	 *
	 * @param CREATOR_USER_ID the creator_user_id of this service request master
	 */
	public void setCREATOR_USER_ID(String CREATOR_USER_ID);

	/**
	 * Returns the creation_date of this service request master.
	 *
	 * @return the creation_date of this service request master
	 */
	public Date getCREATION_DATE();

	/**
	 * Sets the creation_date of this service request master.
	 *
	 * @param CREATION_DATE the creation_date of this service request master
	 */
	public void setCREATION_DATE(Date CREATION_DATE);

	/**
	 * Returns the creator_user_type of this service request master.
	 *
	 * @return the creator_user_type of this service request master
	 */
	@AutoEscape
	public String getCREATOR_USER_TYPE();

	/**
	 * Sets the creator_user_type of this service request master.
	 *
	 * @param CREATOR_USER_TYPE the creator_user_type of this service request master
	 */
	public void setCREATOR_USER_TYPE(String CREATOR_USER_TYPE);

	/**
	 * Returns the assigned_to of this service request master.
	 *
	 * @return the assigned_to of this service request master
	 */
	@AutoEscape
	public String getASSIGNED_TO();

	/**
	 * Sets the assigned_to of this service request master.
	 *
	 * @param ASSIGNED_TO the assigned_to of this service request master
	 */
	public void setASSIGNED_TO(String ASSIGNED_TO);

	/**
	 * Returns the user_name of this service request master.
	 *
	 * @return the user_name of this service request master
	 */
	@AutoEscape
	public String getUSER_NAME();

	/**
	 * Sets the user_name of this service request master.
	 *
	 * @param USER_NAME the user_name of this service request master
	 */
	public void setUSER_NAME(String USER_NAME);

	/**
	 * Returns the iban_number of this service request master.
	 *
	 * @return the iban_number of this service request master
	 */
	@AutoEscape
	public String getIBAN_NUMBER();

	/**
	 * Sets the iban_number of this service request master.
	 *
	 * @param IBAN_NUMBER the iban_number of this service request master
	 */
	public void setIBAN_NUMBER(String IBAN_NUMBER);

	/**
	 * Returns the escalation_flag of this service request master.
	 *
	 * @return the escalation_flag of this service request master
	 */
	public boolean getESCALATION_FLAG();

	/**
	 * Returns <code>true</code> if this service request master is escalation_flag.
	 *
	 * @return <code>true</code> if this service request master is escalation_flag; <code>false</code> otherwise
	 */
	public boolean isESCALATION_FLAG();

	/**
	 * Sets whether this service request master is escalation_flag.
	 *
	 * @param ESCALATION_FLAG the escalation_flag of this service request master
	 */
	public void setESCALATION_FLAG(boolean ESCALATION_FLAG);

}