/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the WorkshopVehicle service. Represents a row in the &quot;EJD_WORKSHOP_VEHICLE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.atmc.acl.db.model.impl.WorkshopVehicleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.atmc.acl.db.model.impl.WorkshopVehicleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WorkshopVehicle
 * @generated
 */
@ProviderType
public interface WorkshopVehicleModel extends BaseModel<WorkshopVehicle> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a workshop vehicle model instance should use the {@link WorkshopVehicle} interface instead.
	 */

	/**
	 * Returns the primary key of this workshop vehicle.
	 *
	 * @return the primary key of this workshop vehicle
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this workshop vehicle.
	 *
	 * @param primaryKey the primary key of this workshop vehicle
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this workshop vehicle.
	 *
	 * @return the ID of this workshop vehicle
	 */
	public int getId();

	/**
	 * Sets the ID of this workshop vehicle.
	 *
	 * @param id the ID of this workshop vehicle
	 */
	public void setId(int id);

	/**
	 * Returns the customer name of this workshop vehicle.
	 *
	 * @return the customer name of this workshop vehicle
	 */
	@AutoEscape
	public String getCustomerName();

	/**
	 * Sets the customer name of this workshop vehicle.
	 *
	 * @param customerName the customer name of this workshop vehicle
	 */
	public void setCustomerName(String customerName);

	/**
	 * Returns the manufacture of this workshop vehicle.
	 *
	 * @return the manufacture of this workshop vehicle
	 */
	@AutoEscape
	public String getManufacture();

	/**
	 * Sets the manufacture of this workshop vehicle.
	 *
	 * @param manufacture the manufacture of this workshop vehicle
	 */
	public void setManufacture(String manufacture);

	/**
	 * Returns the plate no of this workshop vehicle.
	 *
	 * @return the plate no of this workshop vehicle
	 */
	@AutoEscape
	public String getPlateNo();

	/**
	 * Sets the plate no of this workshop vehicle.
	 *
	 * @param plateNo the plate no of this workshop vehicle
	 */
	public void setPlateNo(String plateNo);

	/**
	 * Returns the workshop ID of this workshop vehicle.
	 *
	 * @return the workshop ID of this workshop vehicle
	 */
	public int getWorkshopId();

	/**
	 * Sets the workshop ID of this workshop vehicle.
	 *
	 * @param workshopId the workshop ID of this workshop vehicle
	 */
	public void setWorkshopId(int workshopId);

	/**
	 * Returns the claim ref no of this workshop vehicle.
	 *
	 * @return the claim ref no of this workshop vehicle
	 */
	@AutoEscape
	public String getClaimRefNo();

	/**
	 * Sets the claim ref no of this workshop vehicle.
	 *
	 * @param claimRefNo the claim ref no of this workshop vehicle
	 */
	public void setClaimRefNo(String claimRefNo);

	/**
	 * Returns the status of this workshop vehicle.
	 *
	 * @return the status of this workshop vehicle
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this workshop vehicle.
	 *
	 * @param status the status of this workshop vehicle
	 */
	public void setStatus(String status);

	/**
	 * Returns the date of this workshop vehicle.
	 *
	 * @return the date of this workshop vehicle
	 */
	public Date getDate();

	/**
	 * Sets the date of this workshop vehicle.
	 *
	 * @param date the date of this workshop vehicle
	 */
	public void setDate(Date date);

	/**
	 * Returns the service type of this workshop vehicle.
	 *
	 * @return the service type of this workshop vehicle
	 */
	@AutoEscape
	public String getServiceType();

	/**
	 * Sets the service type of this workshop vehicle.
	 *
	 * @param serviceType the service type of this workshop vehicle
	 */
	public void setServiceType(String serviceType);

	/**
	 * Returns the description of this workshop vehicle.
	 *
	 * @return the description of this workshop vehicle
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this workshop vehicle.
	 *
	 * @param description the description of this workshop vehicle
	 */
	public void setDescription(String description);

	/**
	 * Returns the customer mobile of this workshop vehicle.
	 *
	 * @return the customer mobile of this workshop vehicle
	 */
	@AutoEscape
	public String getCustomerMobile();

	/**
	 * Sets the customer mobile of this workshop vehicle.
	 *
	 * @param customerMobile the customer mobile of this workshop vehicle
	 */
	public void setCustomerMobile(String customerMobile);

	/**
	 * Returns the veh make en of this workshop vehicle.
	 *
	 * @return the veh make en of this workshop vehicle
	 */
	@AutoEscape
	public String getVehMakeEn();

	/**
	 * Sets the veh make en of this workshop vehicle.
	 *
	 * @param vehMakeEn the veh make en of this workshop vehicle
	 */
	public void setVehMakeEn(String vehMakeEn);

	/**
	 * Returns the veh make ar of this workshop vehicle.
	 *
	 * @return the veh make ar of this workshop vehicle
	 */
	@AutoEscape
	public String getVehMakeAr();

	/**
	 * Sets the veh make ar of this workshop vehicle.
	 *
	 * @param vehMakeAr the veh make ar of this workshop vehicle
	 */
	public void setVehMakeAr(String vehMakeAr);

	/**
	 * Returns the veh model en of this workshop vehicle.
	 *
	 * @return the veh model en of this workshop vehicle
	 */
	@AutoEscape
	public String getVehModelEn();

	/**
	 * Sets the veh model en of this workshop vehicle.
	 *
	 * @param vehModelEn the veh model en of this workshop vehicle
	 */
	public void setVehModelEn(String vehModelEn);

	/**
	 * Returns the veh model ar of this workshop vehicle.
	 *
	 * @return the veh model ar of this workshop vehicle
	 */
	@AutoEscape
	public String getVehModelAr();

	/**
	 * Sets the veh model ar of this workshop vehicle.
	 *
	 * @param vehModelAr the veh model ar of this workshop vehicle
	 */
	public void setVehModelAr(String vehModelAr);

	/**
	 * Returns the customer iqama ID of this workshop vehicle.
	 *
	 * @return the customer iqama ID of this workshop vehicle
	 */
	@AutoEscape
	public String getCustomerIqamaId();

	/**
	 * Sets the customer iqama ID of this workshop vehicle.
	 *
	 * @param customerIqamaId the customer iqama ID of this workshop vehicle
	 */
	public void setCustomerIqamaId(String customerIqamaId);

}