
package com.atmc.mob.acl.ws.proxy.yakeen;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Yakeen4AlinmaTMFault", targetNamespace = "http://yakeen4alinmatm.yakeen.elm.com/")
public class Yakeen4AlinmaTMFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Yakeen4AlinmaTMFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Yakeen4AlinmaTMFault_Exception(String message, Yakeen4AlinmaTMFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Yakeen4AlinmaTMFault_Exception(String message, Yakeen4AlinmaTMFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ejada.atmc.acl.ws.proxy.yakeen.Yakeen4AlinmaTMFault
     */
    public Yakeen4AlinmaTMFault getFaultInfo() {
        return faultInfo;
    }

}
