/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model.impl;

import com.ejada.atmc.acl.db.model.CustomerIban;
import com.ejada.atmc.acl.db.model.CustomerIbanModel;
import com.ejada.atmc.acl.db.model.CustomerIbanSoap;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CustomerIban service. Represents a row in the &quot;MDM_CUSTOMER_IBAN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CustomerIbanModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomerIbanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomerIbanImpl
 * @generated
 */
@JSON(strict = true)
public class CustomerIbanModelImpl
	extends BaseModelImpl<CustomerIban> implements CustomerIbanModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a customer iban model instance should use the <code>CustomerIban</code> interface instead.
	 */
	public static final String TABLE_NAME = "MDM_CUSTOMER_IBAN";

	public static final Object[][] TABLE_COLUMNS = {
		{"MDM_CUST_CIVIL_ID", Types.VARCHAR},
		{"MDM_CUST_REF_CODE", Types.VARCHAR},
		{"MDM_PREMIA_CODE", Types.VARCHAR}, {"MDM_IBAN", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("MDM_CUST_CIVIL_ID", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MDM_CUST_REF_CODE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MDM_PREMIA_CODE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MDM_IBAN", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MDM_CUSTOMER_IBAN (MDM_CUST_CIVIL_ID VARCHAR(75) not null primary key,MDM_CUST_REF_CODE VARCHAR(75) null,MDM_PREMIA_CODE VARCHAR(75) null,MDM_IBAN VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table MDM_CUSTOMER_IBAN";

	public static final String ORDER_BY_JPQL = " ORDER BY customerIban.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MDM_CUSTOMER_IBAN.MDM_CUST_CIVIL_ID ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static CustomerIban toModel(CustomerIbanSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CustomerIban model = new CustomerIbanImpl();

		model.setId(soapModel.getId());
		model.setRefCode(soapModel.getRefCode());
		model.setPremiaCCode(soapModel.getPremiaCCode());
		model.setIban(soapModel.getIban());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<CustomerIban> toModels(CustomerIbanSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CustomerIban> models = new ArrayList<CustomerIban>(
			soapModels.length);

		for (CustomerIbanSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CustomerIbanModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return CustomerIban.class;
	}

	@Override
	public String getModelClassName() {
		return CustomerIban.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CustomerIban, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CustomerIban, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CustomerIban, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CustomerIban)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CustomerIban, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CustomerIban, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CustomerIban)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CustomerIban, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CustomerIban, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CustomerIban>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CustomerIban.class.getClassLoader(), CustomerIban.class,
			ModelWrapper.class);

		try {
			Constructor<CustomerIban> constructor =
				(Constructor<CustomerIban>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CustomerIban, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CustomerIban, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CustomerIban, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CustomerIban, Object>>();
		Map<String, BiConsumer<CustomerIban, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CustomerIban, ?>>();

		attributeGetterFunctions.put("id", CustomerIban::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<CustomerIban, String>)CustomerIban::setId);
		attributeGetterFunctions.put("refCode", CustomerIban::getRefCode);
		attributeSetterBiConsumers.put(
			"refCode",
			(BiConsumer<CustomerIban, String>)CustomerIban::setRefCode);
		attributeGetterFunctions.put(
			"premiaCCode", CustomerIban::getPremiaCCode);
		attributeSetterBiConsumers.put(
			"premiaCCode",
			(BiConsumer<CustomerIban, String>)CustomerIban::setPremiaCCode);
		attributeGetterFunctions.put("iban", CustomerIban::getIban);
		attributeSetterBiConsumers.put(
			"iban", (BiConsumer<CustomerIban, String>)CustomerIban::setIban);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getId() {
		if (_id == null) {
			return "";
		}
		else {
			return _id;
		}
	}

	@Override
	public void setId(String id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalId() {
		return getColumnOriginalValue("MDM_CUST_CIVIL_ID");
	}

	@JSON
	@Override
	public String getRefCode() {
		if (_refCode == null) {
			return "";
		}
		else {
			return _refCode;
		}
	}

	@Override
	public void setRefCode(String refCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_refCode = refCode;
	}

	@JSON
	@Override
	public String getPremiaCCode() {
		if (_premiaCCode == null) {
			return "";
		}
		else {
			return _premiaCCode;
		}
	}

	@Override
	public void setPremiaCCode(String premiaCCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_premiaCCode = premiaCCode;
	}

	@JSON
	@Override
	public String getIban() {
		if (_iban == null) {
			return "";
		}
		else {
			return _iban;
		}
	}

	@Override
	public void setIban(String iban) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_iban = iban;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public CustomerIban toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CustomerIban>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CustomerIbanImpl customerIbanImpl = new CustomerIbanImpl();

		customerIbanImpl.setId(getId());
		customerIbanImpl.setRefCode(getRefCode());
		customerIbanImpl.setPremiaCCode(getPremiaCCode());
		customerIbanImpl.setIban(getIban());

		customerIbanImpl.resetOriginalValues();

		return customerIbanImpl;
	}

	@Override
	public int compareTo(CustomerIban customerIban) {
		String primaryKey = customerIban.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CustomerIban)) {
			return false;
		}

		CustomerIban customerIban = (CustomerIban)object;

		String primaryKey = customerIban.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CustomerIban> toCacheModel() {
		CustomerIbanCacheModel customerIbanCacheModel =
			new CustomerIbanCacheModel();

		customerIbanCacheModel.id = getId();

		String id = customerIbanCacheModel.id;

		if ((id != null) && (id.length() == 0)) {
			customerIbanCacheModel.id = null;
		}

		customerIbanCacheModel.refCode = getRefCode();

		String refCode = customerIbanCacheModel.refCode;

		if ((refCode != null) && (refCode.length() == 0)) {
			customerIbanCacheModel.refCode = null;
		}

		customerIbanCacheModel.premiaCCode = getPremiaCCode();

		String premiaCCode = customerIbanCacheModel.premiaCCode;

		if ((premiaCCode != null) && (premiaCCode.length() == 0)) {
			customerIbanCacheModel.premiaCCode = null;
		}

		customerIbanCacheModel.iban = getIban();

		String iban = customerIbanCacheModel.iban;

		if ((iban != null) && (iban.length() == 0)) {
			customerIbanCacheModel.iban = null;
		}

		return customerIbanCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CustomerIban, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CustomerIban, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CustomerIban, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CustomerIban)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CustomerIban, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CustomerIban, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CustomerIban, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CustomerIban)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CustomerIban>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _id;
	private String _refCode;
	private String _premiaCCode;
	private String _iban;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CustomerIban, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CustomerIban)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("MDM_CUST_CIVIL_ID", _id);
		_columnOriginalValues.put("MDM_CUST_REF_CODE", _refCode);
		_columnOriginalValues.put("MDM_PREMIA_CODE", _premiaCCode);
		_columnOriginalValues.put("MDM_IBAN", _iban);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("MDM_CUST_CIVIL_ID", "id");
		attributeNames.put("MDM_CUST_REF_CODE", "refCode");
		attributeNames.put("MDM_PREMIA_CODE", "premiaCCode");
		attributeNames.put("MDM_IBAN", "iban");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("MDM_CUST_CIVIL_ID", 1L);

		columnBitmasks.put("MDM_CUST_REF_CODE", 2L);

		columnBitmasks.put("MDM_PREMIA_CODE", 4L);

		columnBitmasks.put("MDM_IBAN", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CustomerIban _escapedModel;

}