/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model.impl;

import com.ejada.atmc.acl.db.model.PolVEHSearch;
import com.ejada.atmc.acl.db.model.PolVEHSearchModel;
import com.ejada.atmc.acl.db.model.PolVEHSearchSoap;
import com.ejada.atmc.acl.db.service.persistence.PolVEHSearchPK;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PolVEHSearch service. Represents a row in the &quot;ODS_POL_VEH_SEARCH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PolVEHSearchModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolVEHSearchImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PolVEHSearchImpl
 * @generated
 */
@JSON(strict = true)
public class PolVEHSearchModelImpl
	extends BaseModelImpl<PolVEHSearch> implements PolVEHSearchModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pol veh search model instance should use the <code>PolVEHSearch</code> interface instead.
	 */
	public static final String TABLE_NAME = "ODS_POL_VEH_SEARCH";

	public static final Object[][] TABLE_COLUMNS = {
		{"ODS_POLICY_NO", Types.VARCHAR},
		{"ODS_VEHICLE_SEQ_CUSTOM", Types.VARCHAR},
		{"ODS_CHASSIS_NO", Types.VARCHAR},
		{"ODS_VEHICLE_DEF_TYPE", Types.VARCHAR},
		{"ODS_INCEPTION_DT", Types.TIMESTAMP},
		{"ODS_EXPIRY_DT", Types.TIMESTAMP}, {"ODS_ENG_PLATE_NO", Types.BIGINT},
		{"ODS_ENG_PLATE_L1", Types.VARCHAR},
		{"ODS_ENG_PLATE_L2", Types.VARCHAR},
		{"ODS_ENG_PLATE_L3", Types.VARCHAR},
		{"ODS_ARB_PLATE_NO", Types.VARCHAR},
		{"ODS_ARB_PLATE_L1", Types.VARCHAR},
		{"ODS_ARB_PLATE_L2", Types.VARCHAR}, {"ODS_ARB_PLATE_L3", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ODS_POLICY_NO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ODS_VEHICLE_SEQ_CUSTOM", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ODS_CHASSIS_NO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ODS_VEHICLE_DEF_TYPE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ODS_INCEPTION_DT", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ODS_EXPIRY_DT", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ODS_ENG_PLATE_NO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ODS_ENG_PLATE_L1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ODS_ENG_PLATE_L2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ODS_ENG_PLATE_L3", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ODS_ARB_PLATE_NO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ODS_ARB_PLATE_L1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ODS_ARB_PLATE_L2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ODS_ARB_PLATE_L3", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ODS_POL_VEH_SEARCH (ODS_POLICY_NO VARCHAR(75) not null,ODS_VEHICLE_SEQ_CUSTOM VARCHAR(75) not null,ODS_CHASSIS_NO VARCHAR(75) null,ODS_VEHICLE_DEF_TYPE VARCHAR(75) null,ODS_INCEPTION_DT DATE null,ODS_EXPIRY_DT DATE null,ODS_ENG_PLATE_NO LONG,ODS_ENG_PLATE_L1 VARCHAR(75) null,ODS_ENG_PLATE_L2 VARCHAR(75) null,ODS_ENG_PLATE_L3 VARCHAR(75) null,ODS_ARB_PLATE_NO VARCHAR(75) null,ODS_ARB_PLATE_L1 VARCHAR(75) null,ODS_ARB_PLATE_L2 VARCHAR(75) null,ODS_ARB_PLATE_L3 VARCHAR(75) null,primary key (ODS_POLICY_NO, ODS_VEHICLE_SEQ_CUSTOM))";

	public static final String TABLE_SQL_DROP = "drop table ODS_POL_VEH_SEARCH";

	public static final String ORDER_BY_JPQL =
		" ORDER BY polVEHSearch.id.policyNo ASC, polVEHSearch.id.vehicleSEQCustom ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ODS_POL_VEH_SEARCH.ODS_POLICY_NO ASC, ODS_POL_VEH_SEARCH.ODS_VEHICLE_SEQ_CUSTOM ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long POLICYNO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long VEHICLESEQCUSTOM_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static PolVEHSearch toModel(PolVEHSearchSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PolVEHSearch model = new PolVEHSearchImpl();

		model.setPolicyNo(soapModel.getPolicyNo());
		model.setVehicleSEQCustom(soapModel.getVehicleSEQCustom());
		model.setChassisNo(soapModel.getChassisNo());
		model.setVehicleDevType(soapModel.getVehicleDevType());
		model.setInceptionDate(soapModel.getInceptionDate());
		model.setExpiryDate(soapModel.getExpiryDate());
		model.setEngPlateNo(soapModel.getEngPlateNo());
		model.setEngPlateL1(soapModel.getEngPlateL1());
		model.setEngPlateL2(soapModel.getEngPlateL2());
		model.setEngPlateL3(soapModel.getEngPlateL3());
		model.setArbPlateNo(soapModel.getArbPlateNo());
		model.setArbPlateL1(soapModel.getArbPlateL1());
		model.setArbPlateL2(soapModel.getArbPlateL2());
		model.setArbPlateL3(soapModel.getArbPlateL3());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<PolVEHSearch> toModels(PolVEHSearchSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PolVEHSearch> models = new ArrayList<PolVEHSearch>(
			soapModels.length);

		for (PolVEHSearchSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PolVEHSearchModelImpl() {
	}

	@Override
	public PolVEHSearchPK getPrimaryKey() {
		return new PolVEHSearchPK(_policyNo, _vehicleSEQCustom);
	}

	@Override
	public void setPrimaryKey(PolVEHSearchPK primaryKey) {
		setPolicyNo(primaryKey.policyNo);
		setVehicleSEQCustom(primaryKey.vehicleSEQCustom);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new PolVEHSearchPK(_policyNo, _vehicleSEQCustom);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((PolVEHSearchPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return PolVEHSearch.class;
	}

	@Override
	public String getModelClassName() {
		return PolVEHSearch.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PolVEHSearch, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PolVEHSearch, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PolVEHSearch, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PolVEHSearch)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PolVEHSearch, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PolVEHSearch, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PolVEHSearch)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PolVEHSearch, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PolVEHSearch, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PolVEHSearch>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PolVEHSearch.class.getClassLoader(), PolVEHSearch.class,
			ModelWrapper.class);

		try {
			Constructor<PolVEHSearch> constructor =
				(Constructor<PolVEHSearch>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<PolVEHSearch, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PolVEHSearch, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PolVEHSearch, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<PolVEHSearch, Object>>();
		Map<String, BiConsumer<PolVEHSearch, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PolVEHSearch, ?>>();

		attributeGetterFunctions.put("policyNo", PolVEHSearch::getPolicyNo);
		attributeSetterBiConsumers.put(
			"policyNo",
			(BiConsumer<PolVEHSearch, String>)PolVEHSearch::setPolicyNo);
		attributeGetterFunctions.put(
			"vehicleSEQCustom", PolVEHSearch::getVehicleSEQCustom);
		attributeSetterBiConsumers.put(
			"vehicleSEQCustom",
			(BiConsumer<PolVEHSearch, String>)
				PolVEHSearch::setVehicleSEQCustom);
		attributeGetterFunctions.put("chassisNo", PolVEHSearch::getChassisNo);
		attributeSetterBiConsumers.put(
			"chassisNo",
			(BiConsumer<PolVEHSearch, String>)PolVEHSearch::setChassisNo);
		attributeGetterFunctions.put(
			"vehicleDevType", PolVEHSearch::getVehicleDevType);
		attributeSetterBiConsumers.put(
			"vehicleDevType",
			(BiConsumer<PolVEHSearch, String>)PolVEHSearch::setVehicleDevType);
		attributeGetterFunctions.put(
			"inceptionDate", PolVEHSearch::getInceptionDate);
		attributeSetterBiConsumers.put(
			"inceptionDate",
			(BiConsumer<PolVEHSearch, Date>)PolVEHSearch::setInceptionDate);
		attributeGetterFunctions.put("expiryDate", PolVEHSearch::getExpiryDate);
		attributeSetterBiConsumers.put(
			"expiryDate",
			(BiConsumer<PolVEHSearch, Date>)PolVEHSearch::setExpiryDate);
		attributeGetterFunctions.put("engPlateNo", PolVEHSearch::getEngPlateNo);
		attributeSetterBiConsumers.put(
			"engPlateNo",
			(BiConsumer<PolVEHSearch, Long>)PolVEHSearch::setEngPlateNo);
		attributeGetterFunctions.put("engPlateL1", PolVEHSearch::getEngPlateL1);
		attributeSetterBiConsumers.put(
			"engPlateL1",
			(BiConsumer<PolVEHSearch, String>)PolVEHSearch::setEngPlateL1);
		attributeGetterFunctions.put("engPlateL2", PolVEHSearch::getEngPlateL2);
		attributeSetterBiConsumers.put(
			"engPlateL2",
			(BiConsumer<PolVEHSearch, String>)PolVEHSearch::setEngPlateL2);
		attributeGetterFunctions.put("engPlateL3", PolVEHSearch::getEngPlateL3);
		attributeSetterBiConsumers.put(
			"engPlateL3",
			(BiConsumer<PolVEHSearch, String>)PolVEHSearch::setEngPlateL3);
		attributeGetterFunctions.put("arbPlateNo", PolVEHSearch::getArbPlateNo);
		attributeSetterBiConsumers.put(
			"arbPlateNo",
			(BiConsumer<PolVEHSearch, String>)PolVEHSearch::setArbPlateNo);
		attributeGetterFunctions.put("arbPlateL1", PolVEHSearch::getArbPlateL1);
		attributeSetterBiConsumers.put(
			"arbPlateL1",
			(BiConsumer<PolVEHSearch, String>)PolVEHSearch::setArbPlateL1);
		attributeGetterFunctions.put("arbPlateL2", PolVEHSearch::getArbPlateL2);
		attributeSetterBiConsumers.put(
			"arbPlateL2",
			(BiConsumer<PolVEHSearch, String>)PolVEHSearch::setArbPlateL2);
		attributeGetterFunctions.put("arbPlateL3", PolVEHSearch::getArbPlateL3);
		attributeSetterBiConsumers.put(
			"arbPlateL3",
			(BiConsumer<PolVEHSearch, String>)PolVEHSearch::setArbPlateL3);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getPolicyNo() {
		if (_policyNo == null) {
			return "";
		}
		else {
			return _policyNo;
		}
	}

	@Override
	public void setPolicyNo(String policyNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyNo = policyNo;
	}

	@JSON
	@Override
	public String getVehicleSEQCustom() {
		if (_vehicleSEQCustom == null) {
			return "";
		}
		else {
			return _vehicleSEQCustom;
		}
	}

	@Override
	public void setVehicleSEQCustom(String vehicleSEQCustom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleSEQCustom = vehicleSEQCustom;
	}

	@JSON
	@Override
	public String getChassisNo() {
		if (_chassisNo == null) {
			return "";
		}
		else {
			return _chassisNo;
		}
	}

	@Override
	public void setChassisNo(String chassisNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_chassisNo = chassisNo;
	}

	@JSON
	@Override
	public String getVehicleDevType() {
		if (_vehicleDevType == null) {
			return "";
		}
		else {
			return _vehicleDevType;
		}
	}

	@Override
	public void setVehicleDevType(String vehicleDevType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleDevType = vehicleDevType;
	}

	@JSON
	@Override
	public Date getInceptionDate() {
		return _inceptionDate;
	}

	@Override
	public void setInceptionDate(Date inceptionDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_inceptionDate = inceptionDate;
	}

	@JSON
	@Override
	public Date getExpiryDate() {
		return _expiryDate;
	}

	@Override
	public void setExpiryDate(Date expiryDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expiryDate = expiryDate;
	}

	@JSON
	@Override
	public long getEngPlateNo() {
		return _engPlateNo;
	}

	@Override
	public void setEngPlateNo(long engPlateNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_engPlateNo = engPlateNo;
	}

	@JSON
	@Override
	public String getEngPlateL1() {
		if (_engPlateL1 == null) {
			return "";
		}
		else {
			return _engPlateL1;
		}
	}

	@Override
	public void setEngPlateL1(String engPlateL1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_engPlateL1 = engPlateL1;
	}

	@JSON
	@Override
	public String getEngPlateL2() {
		if (_engPlateL2 == null) {
			return "";
		}
		else {
			return _engPlateL2;
		}
	}

	@Override
	public void setEngPlateL2(String engPlateL2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_engPlateL2 = engPlateL2;
	}

	@JSON
	@Override
	public String getEngPlateL3() {
		if (_engPlateL3 == null) {
			return "";
		}
		else {
			return _engPlateL3;
		}
	}

	@Override
	public void setEngPlateL3(String engPlateL3) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_engPlateL3 = engPlateL3;
	}

	@JSON
	@Override
	public String getArbPlateNo() {
		if (_arbPlateNo == null) {
			return "";
		}
		else {
			return _arbPlateNo;
		}
	}

	@Override
	public void setArbPlateNo(String arbPlateNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_arbPlateNo = arbPlateNo;
	}

	@JSON
	@Override
	public String getArbPlateL1() {
		if (_arbPlateL1 == null) {
			return "";
		}
		else {
			return _arbPlateL1;
		}
	}

	@Override
	public void setArbPlateL1(String arbPlateL1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_arbPlateL1 = arbPlateL1;
	}

	@JSON
	@Override
	public String getArbPlateL2() {
		if (_arbPlateL2 == null) {
			return "";
		}
		else {
			return _arbPlateL2;
		}
	}

	@Override
	public void setArbPlateL2(String arbPlateL2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_arbPlateL2 = arbPlateL2;
	}

	@JSON
	@Override
	public String getArbPlateL3() {
		if (_arbPlateL3 == null) {
			return "";
		}
		else {
			return _arbPlateL3;
		}
	}

	@Override
	public void setArbPlateL3(String arbPlateL3) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_arbPlateL3 = arbPlateL3;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public PolVEHSearch toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PolVEHSearch>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PolVEHSearchImpl polVEHSearchImpl = new PolVEHSearchImpl();

		polVEHSearchImpl.setPolicyNo(getPolicyNo());
		polVEHSearchImpl.setVehicleSEQCustom(getVehicleSEQCustom());
		polVEHSearchImpl.setChassisNo(getChassisNo());
		polVEHSearchImpl.setVehicleDevType(getVehicleDevType());
		polVEHSearchImpl.setInceptionDate(getInceptionDate());
		polVEHSearchImpl.setExpiryDate(getExpiryDate());
		polVEHSearchImpl.setEngPlateNo(getEngPlateNo());
		polVEHSearchImpl.setEngPlateL1(getEngPlateL1());
		polVEHSearchImpl.setEngPlateL2(getEngPlateL2());
		polVEHSearchImpl.setEngPlateL3(getEngPlateL3());
		polVEHSearchImpl.setArbPlateNo(getArbPlateNo());
		polVEHSearchImpl.setArbPlateL1(getArbPlateL1());
		polVEHSearchImpl.setArbPlateL2(getArbPlateL2());
		polVEHSearchImpl.setArbPlateL3(getArbPlateL3());

		polVEHSearchImpl.resetOriginalValues();

		return polVEHSearchImpl;
	}

	@Override
	public int compareTo(PolVEHSearch polVEHSearch) {
		PolVEHSearchPK primaryKey = polVEHSearch.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PolVEHSearch)) {
			return false;
		}

		PolVEHSearch polVEHSearch = (PolVEHSearch)object;

		PolVEHSearchPK primaryKey = polVEHSearch.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PolVEHSearch> toCacheModel() {
		PolVEHSearchCacheModel polVEHSearchCacheModel =
			new PolVEHSearchCacheModel();

		polVEHSearchCacheModel.polVEHSearchPK = getPrimaryKey();

		polVEHSearchCacheModel.policyNo = getPolicyNo();

		String policyNo = polVEHSearchCacheModel.policyNo;

		if ((policyNo != null) && (policyNo.length() == 0)) {
			polVEHSearchCacheModel.policyNo = null;
		}

		polVEHSearchCacheModel.vehicleSEQCustom = getVehicleSEQCustom();

		String vehicleSEQCustom = polVEHSearchCacheModel.vehicleSEQCustom;

		if ((vehicleSEQCustom != null) && (vehicleSEQCustom.length() == 0)) {
			polVEHSearchCacheModel.vehicleSEQCustom = null;
		}

		polVEHSearchCacheModel.chassisNo = getChassisNo();

		String chassisNo = polVEHSearchCacheModel.chassisNo;

		if ((chassisNo != null) && (chassisNo.length() == 0)) {
			polVEHSearchCacheModel.chassisNo = null;
		}

		polVEHSearchCacheModel.vehicleDevType = getVehicleDevType();

		String vehicleDevType = polVEHSearchCacheModel.vehicleDevType;

		if ((vehicleDevType != null) && (vehicleDevType.length() == 0)) {
			polVEHSearchCacheModel.vehicleDevType = null;
		}

		Date inceptionDate = getInceptionDate();

		if (inceptionDate != null) {
			polVEHSearchCacheModel.inceptionDate = inceptionDate.getTime();
		}
		else {
			polVEHSearchCacheModel.inceptionDate = Long.MIN_VALUE;
		}

		Date expiryDate = getExpiryDate();

		if (expiryDate != null) {
			polVEHSearchCacheModel.expiryDate = expiryDate.getTime();
		}
		else {
			polVEHSearchCacheModel.expiryDate = Long.MIN_VALUE;
		}

		polVEHSearchCacheModel.engPlateNo = getEngPlateNo();

		polVEHSearchCacheModel.engPlateL1 = getEngPlateL1();

		String engPlateL1 = polVEHSearchCacheModel.engPlateL1;

		if ((engPlateL1 != null) && (engPlateL1.length() == 0)) {
			polVEHSearchCacheModel.engPlateL1 = null;
		}

		polVEHSearchCacheModel.engPlateL2 = getEngPlateL2();

		String engPlateL2 = polVEHSearchCacheModel.engPlateL2;

		if ((engPlateL2 != null) && (engPlateL2.length() == 0)) {
			polVEHSearchCacheModel.engPlateL2 = null;
		}

		polVEHSearchCacheModel.engPlateL3 = getEngPlateL3();

		String engPlateL3 = polVEHSearchCacheModel.engPlateL3;

		if ((engPlateL3 != null) && (engPlateL3.length() == 0)) {
			polVEHSearchCacheModel.engPlateL3 = null;
		}

		polVEHSearchCacheModel.arbPlateNo = getArbPlateNo();

		String arbPlateNo = polVEHSearchCacheModel.arbPlateNo;

		if ((arbPlateNo != null) && (arbPlateNo.length() == 0)) {
			polVEHSearchCacheModel.arbPlateNo = null;
		}

		polVEHSearchCacheModel.arbPlateL1 = getArbPlateL1();

		String arbPlateL1 = polVEHSearchCacheModel.arbPlateL1;

		if ((arbPlateL1 != null) && (arbPlateL1.length() == 0)) {
			polVEHSearchCacheModel.arbPlateL1 = null;
		}

		polVEHSearchCacheModel.arbPlateL2 = getArbPlateL2();

		String arbPlateL2 = polVEHSearchCacheModel.arbPlateL2;

		if ((arbPlateL2 != null) && (arbPlateL2.length() == 0)) {
			polVEHSearchCacheModel.arbPlateL2 = null;
		}

		polVEHSearchCacheModel.arbPlateL3 = getArbPlateL3();

		String arbPlateL3 = polVEHSearchCacheModel.arbPlateL3;

		if ((arbPlateL3 != null) && (arbPlateL3.length() == 0)) {
			polVEHSearchCacheModel.arbPlateL3 = null;
		}

		return polVEHSearchCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PolVEHSearch, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PolVEHSearch, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PolVEHSearch, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((PolVEHSearch)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PolVEHSearch, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PolVEHSearch, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PolVEHSearch, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PolVEHSearch)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PolVEHSearch>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _policyNo;
	private String _vehicleSEQCustom;
	private String _chassisNo;
	private String _vehicleDevType;
	private Date _inceptionDate;
	private Date _expiryDate;
	private long _engPlateNo;
	private String _engPlateL1;
	private String _engPlateL2;
	private String _engPlateL3;
	private String _arbPlateNo;
	private String _arbPlateL1;
	private String _arbPlateL2;
	private String _arbPlateL3;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PolVEHSearch, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PolVEHSearch)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("ODS_POLICY_NO", _policyNo);
		_columnOriginalValues.put("ODS_VEHICLE_SEQ_CUSTOM", _vehicleSEQCustom);
		_columnOriginalValues.put("ODS_CHASSIS_NO", _chassisNo);
		_columnOriginalValues.put("ODS_VEHICLE_DEF_TYPE", _vehicleDevType);
		_columnOriginalValues.put("ODS_INCEPTION_DT", _inceptionDate);
		_columnOriginalValues.put("ODS_EXPIRY_DT", _expiryDate);
		_columnOriginalValues.put("ODS_ENG_PLATE_NO", _engPlateNo);
		_columnOriginalValues.put("ODS_ENG_PLATE_L1", _engPlateL1);
		_columnOriginalValues.put("ODS_ENG_PLATE_L2", _engPlateL2);
		_columnOriginalValues.put("ODS_ENG_PLATE_L3", _engPlateL3);
		_columnOriginalValues.put("ODS_ARB_PLATE_NO", _arbPlateNo);
		_columnOriginalValues.put("ODS_ARB_PLATE_L1", _arbPlateL1);
		_columnOriginalValues.put("ODS_ARB_PLATE_L2", _arbPlateL2);
		_columnOriginalValues.put("ODS_ARB_PLATE_L3", _arbPlateL3);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("ODS_POLICY_NO", "policyNo");
		attributeNames.put("ODS_VEHICLE_SEQ_CUSTOM", "vehicleSEQCustom");
		attributeNames.put("ODS_CHASSIS_NO", "chassisNo");
		attributeNames.put("ODS_VEHICLE_DEF_TYPE", "vehicleDevType");
		attributeNames.put("ODS_INCEPTION_DT", "inceptionDate");
		attributeNames.put("ODS_EXPIRY_DT", "expiryDate");
		attributeNames.put("ODS_ENG_PLATE_NO", "engPlateNo");
		attributeNames.put("ODS_ENG_PLATE_L1", "engPlateL1");
		attributeNames.put("ODS_ENG_PLATE_L2", "engPlateL2");
		attributeNames.put("ODS_ENG_PLATE_L3", "engPlateL3");
		attributeNames.put("ODS_ARB_PLATE_NO", "arbPlateNo");
		attributeNames.put("ODS_ARB_PLATE_L1", "arbPlateL1");
		attributeNames.put("ODS_ARB_PLATE_L2", "arbPlateL2");
		attributeNames.put("ODS_ARB_PLATE_L3", "arbPlateL3");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("ODS_POLICY_NO", 1L);

		columnBitmasks.put("ODS_VEHICLE_SEQ_CUSTOM", 2L);

		columnBitmasks.put("ODS_CHASSIS_NO", 4L);

		columnBitmasks.put("ODS_VEHICLE_DEF_TYPE", 8L);

		columnBitmasks.put("ODS_INCEPTION_DT", 16L);

		columnBitmasks.put("ODS_EXPIRY_DT", 32L);

		columnBitmasks.put("ODS_ENG_PLATE_NO", 64L);

		columnBitmasks.put("ODS_ENG_PLATE_L1", 128L);

		columnBitmasks.put("ODS_ENG_PLATE_L2", 256L);

		columnBitmasks.put("ODS_ENG_PLATE_L3", 512L);

		columnBitmasks.put("ODS_ARB_PLATE_NO", 1024L);

		columnBitmasks.put("ODS_ARB_PLATE_L1", 2048L);

		columnBitmasks.put("ODS_ARB_PLATE_L2", 4096L);

		columnBitmasks.put("ODS_ARB_PLATE_L3", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PolVEHSearch _escapedModel;

}