/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model.impl;

import com.ejada.atmc.acl.db.model.QuotationAdminUploads;
import com.ejada.atmc.acl.db.model.QuotationAdminUploadsAdminFileBlobModel;
import com.ejada.atmc.acl.db.model.QuotationAdminUploadsModel;
import com.ejada.atmc.acl.db.model.QuotationAdminUploadsSoap;
import com.ejada.atmc.acl.db.service.QuotationAdminUploadsLocalServiceUtil;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the QuotationAdminUploads service. Represents a row in the &quot;EJD_QUOTATIONS_ADMIN_UPLOADS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>QuotationAdminUploadsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QuotationAdminUploadsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuotationAdminUploadsImpl
 * @generated
 */
@JSON(strict = true)
public class QuotationAdminUploadsModelImpl
	extends BaseModelImpl<QuotationAdminUploads>
	implements QuotationAdminUploadsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a quotation admin uploads model instance should use the <code>QuotationAdminUploads</code> interface instead.
	 */
	public static final String TABLE_NAME = "EJD_QUOTATIONS_ADMIN_UPLOADS";

	public static final Object[][] TABLE_COLUMNS = {
		{"ID", Types.INTEGER}, {"QUOTATION_ID", Types.BIGINT},
		{"FILE_NAME", Types.VARCHAR}, {"ADMIN_FILE", Types.BLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ID", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("QUOTATION_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FILE_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ADMIN_FILE", Types.BLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EJD_QUOTATIONS_ADMIN_UPLOADS (ID INTEGER not null primary key,QUOTATION_ID LONG,FILE_NAME VARCHAR(75) null,ADMIN_FILE BLOB)";

	public static final String TABLE_SQL_DROP =
		"drop table EJD_QUOTATIONS_ADMIN_UPLOADS";

	public static final String ORDER_BY_JPQL =
		" ORDER BY quotationAdminUploads.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EJD_QUOTATIONS_ADMIN_UPLOADS.ID ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long QUOTATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static QuotationAdminUploads toModel(
		QuotationAdminUploadsSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		QuotationAdminUploads model = new QuotationAdminUploadsImpl();

		model.setId(soapModel.getId());
		model.setQuotationId(soapModel.getQuotationId());
		model.setFileName(soapModel.getFileName());
		model.setAdminFile(soapModel.getAdminFile());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<QuotationAdminUploads> toModels(
		QuotationAdminUploadsSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<QuotationAdminUploads> models =
			new ArrayList<QuotationAdminUploads>(soapModels.length);

		for (QuotationAdminUploadsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public QuotationAdminUploadsModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QuotationAdminUploads.class;
	}

	@Override
	public String getModelClassName() {
		return QuotationAdminUploads.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<QuotationAdminUploads, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<QuotationAdminUploads, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<QuotationAdminUploads, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((QuotationAdminUploads)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<QuotationAdminUploads, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<QuotationAdminUploads, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(QuotationAdminUploads)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<QuotationAdminUploads, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<QuotationAdminUploads, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, QuotationAdminUploads>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			QuotationAdminUploads.class.getClassLoader(),
			QuotationAdminUploads.class, ModelWrapper.class);

		try {
			Constructor<QuotationAdminUploads> constructor =
				(Constructor<QuotationAdminUploads>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<QuotationAdminUploads, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<QuotationAdminUploads, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<QuotationAdminUploads, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<QuotationAdminUploads, Object>>();
		Map<String, BiConsumer<QuotationAdminUploads, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<QuotationAdminUploads, ?>>();

		attributeGetterFunctions.put("id", QuotationAdminUploads::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<QuotationAdminUploads, Integer>)
				QuotationAdminUploads::setId);
		attributeGetterFunctions.put(
			"quotationId", QuotationAdminUploads::getQuotationId);
		attributeSetterBiConsumers.put(
			"quotationId",
			(BiConsumer<QuotationAdminUploads, Long>)
				QuotationAdminUploads::setQuotationId);
		attributeGetterFunctions.put(
			"fileName", QuotationAdminUploads::getFileName);
		attributeSetterBiConsumers.put(
			"fileName",
			(BiConsumer<QuotationAdminUploads, String>)
				QuotationAdminUploads::setFileName);
		attributeGetterFunctions.put(
			"adminFile", QuotationAdminUploads::getAdminFile);
		attributeSetterBiConsumers.put(
			"adminFile",
			(BiConsumer<QuotationAdminUploads, Blob>)
				QuotationAdminUploads::setAdminFile);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getQuotationId() {
		return _quotationId;
	}

	@Override
	public void setQuotationId(long quotationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_quotationId = quotationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalQuotationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("QUOTATION_ID"));
	}

	@JSON
	@Override
	public String getFileName() {
		if (_fileName == null) {
			return "";
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileName = fileName;
	}

	@JSON
	@Override
	public Blob getAdminFile() {
		if (_adminFileBlobModel == null) {
			try {
				_adminFileBlobModel =
					QuotationAdminUploadsLocalServiceUtil.getAdminFileBlobModel(
						getPrimaryKey());
			}
			catch (Exception exception) {
			}
		}

		Blob blob = null;

		if (_adminFileBlobModel != null) {
			blob = _adminFileBlobModel.getAdminFileBlob();
		}

		return blob;
	}

	@Override
	public void setAdminFile(Blob adminFile) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		if (_adminFileBlobModel == null) {
			_adminFileBlobModel = new QuotationAdminUploadsAdminFileBlobModel(
				getPrimaryKey(), adminFile);
		}
		else {
			_adminFileBlobModel.setAdminFileBlob(adminFile);
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public QuotationAdminUploads toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, QuotationAdminUploads>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QuotationAdminUploadsImpl quotationAdminUploadsImpl =
			new QuotationAdminUploadsImpl();

		quotationAdminUploadsImpl.setId(getId());
		quotationAdminUploadsImpl.setQuotationId(getQuotationId());
		quotationAdminUploadsImpl.setFileName(getFileName());

		quotationAdminUploadsImpl.resetOriginalValues();

		return quotationAdminUploadsImpl;
	}

	@Override
	public int compareTo(QuotationAdminUploads quotationAdminUploads) {
		int primaryKey = quotationAdminUploads.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof QuotationAdminUploads)) {
			return false;
		}

		QuotationAdminUploads quotationAdminUploads =
			(QuotationAdminUploads)object;

		int primaryKey = quotationAdminUploads.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_adminFileBlobModel = null;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<QuotationAdminUploads> toCacheModel() {
		QuotationAdminUploadsCacheModel quotationAdminUploadsCacheModel =
			new QuotationAdminUploadsCacheModel();

		quotationAdminUploadsCacheModel.id = getId();

		quotationAdminUploadsCacheModel.quotationId = getQuotationId();

		quotationAdminUploadsCacheModel.fileName = getFileName();

		String fileName = quotationAdminUploadsCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			quotationAdminUploadsCacheModel.fileName = null;
		}

		return quotationAdminUploadsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", quotationId=");
		sb.append(getQuotationId());
		sb.append(", fileName=");
		sb.append(getFileName());

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.ejada.atmc.acl.db.model.QuotationAdminUploads");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quotationId</column-name><column-value><![CDATA[");
		sb.append(getQuotationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileName</column-name><column-value><![CDATA[");
		sb.append(getFileName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, QuotationAdminUploads>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private int _id;
	private long _quotationId;
	private String _fileName;
	private QuotationAdminUploadsAdminFileBlobModel _adminFileBlobModel;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<QuotationAdminUploads, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((QuotationAdminUploads)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("ID", _id);
		_columnOriginalValues.put("QUOTATION_ID", _quotationId);
		_columnOriginalValues.put("FILE_NAME", _fileName);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("ID", "id");
		attributeNames.put("QUOTATION_ID", "quotationId");
		attributeNames.put("FILE_NAME", "fileName");
		attributeNames.put("ADMIN_FILE", "adminFile");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("ID", 1L);

		columnBitmasks.put("QUOTATION_ID", 2L);

		columnBitmasks.put("FILE_NAME", 4L);

		columnBitmasks.put("ADMIN_FILE", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private QuotationAdminUploads _escapedModel;

}