/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model.impl;

import com.ejada.atmc.acl.db.model.QuotationExtraTameeniInfo;
import com.ejada.atmc.acl.db.model.QuotationExtraTameeniInfoModel;
import com.ejada.atmc.acl.db.model.QuotationExtraTameeniInfoSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the QuotationExtraTameeniInfo service. Represents a row in the &quot;EJD_QUOTATIONS_TAMEENI_EXTRAS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>QuotationExtraTameeniInfoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QuotationExtraTameeniInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuotationExtraTameeniInfoImpl
 * @generated
 */
@JSON(strict = true)
public class QuotationExtraTameeniInfoModelImpl
	extends BaseModelImpl<QuotationExtraTameeniInfo>
	implements QuotationExtraTameeniInfoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a quotation extra tameeni info model instance should use the <code>QuotationExtraTameeniInfo</code> interface instead.
	 */
	public static final String TABLE_NAME = "EJD_QUOTATIONS_TAMEENI_EXTRAS";

	public static final Object[][] TABLE_COLUMNS = {
		{"QUOTATION_ID", Types.BIGINT}, {"INSURED_FIRST_NAME", Types.VARCHAR},
		{"INSURED_MIDDLE_NAME", Types.VARCHAR},
		{"INSURED_LAST_NAME", Types.VARCHAR},
		{"IS_DRIVER_DISABLED", Types.BOOLEAN},
		{"VEHICLE_MAKE_CODE_TAMEENI", Types.BIGINT},
		{"COVER_AGE_LIMIT", Types.BIGINT}, {"INSURED_NAME_LANG", Types.VARCHAR},
		{"POLICY_TITLE_ID", Types.VARCHAR}, {"IS_RENEWAL", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("QUOTATION_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("INSURED_FIRST_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("INSURED_MIDDLE_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("INSURED_LAST_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("IS_DRIVER_DISABLED", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("VEHICLE_MAKE_CODE_TAMEENI", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("COVER_AGE_LIMIT", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("INSURED_NAME_LANG", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("POLICY_TITLE_ID", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("IS_RENEWAL", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EJD_QUOTATIONS_TAMEENI_EXTRAS (QUOTATION_ID LONG not null primary key,INSURED_FIRST_NAME VARCHAR(75) null,INSURED_MIDDLE_NAME VARCHAR(75) null,INSURED_LAST_NAME VARCHAR(75) null,IS_DRIVER_DISABLED BOOLEAN,VEHICLE_MAKE_CODE_TAMEENI LONG,COVER_AGE_LIMIT LONG,INSURED_NAME_LANG VARCHAR(75) null,POLICY_TITLE_ID VARCHAR(75) null,IS_RENEWAL BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table EJD_QUOTATIONS_TAMEENI_EXTRAS";

	public static final String ORDER_BY_JPQL =
		" ORDER BY quotationExtraTameeniInfo.quotationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EJD_QUOTATIONS_TAMEENI_EXTRAS.QUOTATION_ID ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long QUOTATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static QuotationExtraTameeniInfo toModel(
		QuotationExtraTameeniInfoSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		QuotationExtraTameeniInfo model = new QuotationExtraTameeniInfoImpl();

		model.setQuotationId(soapModel.getQuotationId());
		model.setInsuredFirstName(soapModel.getInsuredFirstName());
		model.setInsuredMiddleName(soapModel.getInsuredMiddleName());
		model.setInsuredLastName(soapModel.getInsuredLastName());
		model.setIsDriverDisabled(soapModel.isIsDriverDisabled());
		model.setVehicleMakeCodeTameeni(soapModel.getVehicleMakeCodeTameeni());
		model.setCoverAgeLimit(soapModel.getCoverAgeLimit());
		model.setInsuredNameLang(soapModel.getInsuredNameLang());
		model.setPolicyTitleId(soapModel.getPolicyTitleId());
		model.setIsRenewal(soapModel.isIsRenewal());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<QuotationExtraTameeniInfo> toModels(
		QuotationExtraTameeniInfoSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<QuotationExtraTameeniInfo> models =
			new ArrayList<QuotationExtraTameeniInfo>(soapModels.length);

		for (QuotationExtraTameeniInfoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public QuotationExtraTameeniInfoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _quotationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setQuotationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _quotationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QuotationExtraTameeniInfo.class;
	}

	@Override
	public String getModelClassName() {
		return QuotationExtraTameeniInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<QuotationExtraTameeniInfo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<QuotationExtraTameeniInfo, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<QuotationExtraTameeniInfo, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((QuotationExtraTameeniInfo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<QuotationExtraTameeniInfo, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<QuotationExtraTameeniInfo, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(QuotationExtraTameeniInfo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<QuotationExtraTameeniInfo, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<QuotationExtraTameeniInfo, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, QuotationExtraTameeniInfo>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			QuotationExtraTameeniInfo.class.getClassLoader(),
			QuotationExtraTameeniInfo.class, ModelWrapper.class);

		try {
			Constructor<QuotationExtraTameeniInfo> constructor =
				(Constructor<QuotationExtraTameeniInfo>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<QuotationExtraTameeniInfo, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<QuotationExtraTameeniInfo, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<QuotationExtraTameeniInfo, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<QuotationExtraTameeniInfo, Object>>();
		Map<String, BiConsumer<QuotationExtraTameeniInfo, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<QuotationExtraTameeniInfo, ?>>();

		attributeGetterFunctions.put(
			"quotationId", QuotationExtraTameeniInfo::getQuotationId);
		attributeSetterBiConsumers.put(
			"quotationId",
			(BiConsumer<QuotationExtraTameeniInfo, Long>)
				QuotationExtraTameeniInfo::setQuotationId);
		attributeGetterFunctions.put(
			"insuredFirstName", QuotationExtraTameeniInfo::getInsuredFirstName);
		attributeSetterBiConsumers.put(
			"insuredFirstName",
			(BiConsumer<QuotationExtraTameeniInfo, String>)
				QuotationExtraTameeniInfo::setInsuredFirstName);
		attributeGetterFunctions.put(
			"insuredMiddleName",
			QuotationExtraTameeniInfo::getInsuredMiddleName);
		attributeSetterBiConsumers.put(
			"insuredMiddleName",
			(BiConsumer<QuotationExtraTameeniInfo, String>)
				QuotationExtraTameeniInfo::setInsuredMiddleName);
		attributeGetterFunctions.put(
			"insuredLastName", QuotationExtraTameeniInfo::getInsuredLastName);
		attributeSetterBiConsumers.put(
			"insuredLastName",
			(BiConsumer<QuotationExtraTameeniInfo, String>)
				QuotationExtraTameeniInfo::setInsuredLastName);
		attributeGetterFunctions.put(
			"isDriverDisabled", QuotationExtraTameeniInfo::getIsDriverDisabled);
		attributeSetterBiConsumers.put(
			"isDriverDisabled",
			(BiConsumer<QuotationExtraTameeniInfo, Boolean>)
				QuotationExtraTameeniInfo::setIsDriverDisabled);
		attributeGetterFunctions.put(
			"vehicleMakeCodeTameeni",
			QuotationExtraTameeniInfo::getVehicleMakeCodeTameeni);
		attributeSetterBiConsumers.put(
			"vehicleMakeCodeTameeni",
			(BiConsumer<QuotationExtraTameeniInfo, Long>)
				QuotationExtraTameeniInfo::setVehicleMakeCodeTameeni);
		attributeGetterFunctions.put(
			"coverAgeLimit", QuotationExtraTameeniInfo::getCoverAgeLimit);
		attributeSetterBiConsumers.put(
			"coverAgeLimit",
			(BiConsumer<QuotationExtraTameeniInfo, Long>)
				QuotationExtraTameeniInfo::setCoverAgeLimit);
		attributeGetterFunctions.put(
			"insuredNameLang", QuotationExtraTameeniInfo::getInsuredNameLang);
		attributeSetterBiConsumers.put(
			"insuredNameLang",
			(BiConsumer<QuotationExtraTameeniInfo, String>)
				QuotationExtraTameeniInfo::setInsuredNameLang);
		attributeGetterFunctions.put(
			"policyTitleId", QuotationExtraTameeniInfo::getPolicyTitleId);
		attributeSetterBiConsumers.put(
			"policyTitleId",
			(BiConsumer<QuotationExtraTameeniInfo, String>)
				QuotationExtraTameeniInfo::setPolicyTitleId);
		attributeGetterFunctions.put(
			"isRenewal", QuotationExtraTameeniInfo::getIsRenewal);
		attributeSetterBiConsumers.put(
			"isRenewal",
			(BiConsumer<QuotationExtraTameeniInfo, Boolean>)
				QuotationExtraTameeniInfo::setIsRenewal);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getQuotationId() {
		return _quotationId;
	}

	@Override
	public void setQuotationId(long quotationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_quotationId = quotationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalQuotationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("QUOTATION_ID"));
	}

	@JSON
	@Override
	public String getInsuredFirstName() {
		if (_insuredFirstName == null) {
			return "";
		}
		else {
			return _insuredFirstName;
		}
	}

	@Override
	public void setInsuredFirstName(String insuredFirstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_insuredFirstName = insuredFirstName;
	}

	@JSON
	@Override
	public String getInsuredMiddleName() {
		if (_insuredMiddleName == null) {
			return "";
		}
		else {
			return _insuredMiddleName;
		}
	}

	@Override
	public void setInsuredMiddleName(String insuredMiddleName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_insuredMiddleName = insuredMiddleName;
	}

	@JSON
	@Override
	public String getInsuredLastName() {
		if (_insuredLastName == null) {
			return "";
		}
		else {
			return _insuredLastName;
		}
	}

	@Override
	public void setInsuredLastName(String insuredLastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_insuredLastName = insuredLastName;
	}

	@JSON
	@Override
	public boolean getIsDriverDisabled() {
		return _isDriverDisabled;
	}

	@JSON
	@Override
	public boolean isIsDriverDisabled() {
		return _isDriverDisabled;
	}

	@Override
	public void setIsDriverDisabled(boolean isDriverDisabled) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isDriverDisabled = isDriverDisabled;
	}

	@JSON
	@Override
	public long getVehicleMakeCodeTameeni() {
		return _vehicleMakeCodeTameeni;
	}

	@Override
	public void setVehicleMakeCodeTameeni(long vehicleMakeCodeTameeni) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleMakeCodeTameeni = vehicleMakeCodeTameeni;
	}

	@JSON
	@Override
	public long getCoverAgeLimit() {
		return _coverAgeLimit;
	}

	@Override
	public void setCoverAgeLimit(long coverAgeLimit) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_coverAgeLimit = coverAgeLimit;
	}

	@JSON
	@Override
	public String getInsuredNameLang() {
		if (_insuredNameLang == null) {
			return "";
		}
		else {
			return _insuredNameLang;
		}
	}

	@Override
	public void setInsuredNameLang(String insuredNameLang) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_insuredNameLang = insuredNameLang;
	}

	@JSON
	@Override
	public String getPolicyTitleId() {
		if (_policyTitleId == null) {
			return "";
		}
		else {
			return _policyTitleId;
		}
	}

	@Override
	public void setPolicyTitleId(String policyTitleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyTitleId = policyTitleId;
	}

	@JSON
	@Override
	public boolean getIsRenewal() {
		return _isRenewal;
	}

	@JSON
	@Override
	public boolean isIsRenewal() {
		return _isRenewal;
	}

	@Override
	public void setIsRenewal(boolean isRenewal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isRenewal = isRenewal;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, QuotationExtraTameeniInfo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QuotationExtraTameeniInfo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, QuotationExtraTameeniInfo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QuotationExtraTameeniInfoImpl quotationExtraTameeniInfoImpl =
			new QuotationExtraTameeniInfoImpl();

		quotationExtraTameeniInfoImpl.setQuotationId(getQuotationId());
		quotationExtraTameeniInfoImpl.setInsuredFirstName(
			getInsuredFirstName());
		quotationExtraTameeniInfoImpl.setInsuredMiddleName(
			getInsuredMiddleName());
		quotationExtraTameeniInfoImpl.setInsuredLastName(getInsuredLastName());
		quotationExtraTameeniInfoImpl.setIsDriverDisabled(isIsDriverDisabled());
		quotationExtraTameeniInfoImpl.setVehicleMakeCodeTameeni(
			getVehicleMakeCodeTameeni());
		quotationExtraTameeniInfoImpl.setCoverAgeLimit(getCoverAgeLimit());
		quotationExtraTameeniInfoImpl.setInsuredNameLang(getInsuredNameLang());
		quotationExtraTameeniInfoImpl.setPolicyTitleId(getPolicyTitleId());
		quotationExtraTameeniInfoImpl.setIsRenewal(isIsRenewal());

		quotationExtraTameeniInfoImpl.resetOriginalValues();

		return quotationExtraTameeniInfoImpl;
	}

	@Override
	public int compareTo(QuotationExtraTameeniInfo quotationExtraTameeniInfo) {
		long primaryKey = quotationExtraTameeniInfo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof QuotationExtraTameeniInfo)) {
			return false;
		}

		QuotationExtraTameeniInfo quotationExtraTameeniInfo =
			(QuotationExtraTameeniInfo)object;

		long primaryKey = quotationExtraTameeniInfo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<QuotationExtraTameeniInfo> toCacheModel() {
		QuotationExtraTameeniInfoCacheModel
			quotationExtraTameeniInfoCacheModel =
				new QuotationExtraTameeniInfoCacheModel();

		quotationExtraTameeniInfoCacheModel.quotationId = getQuotationId();

		quotationExtraTameeniInfoCacheModel.insuredFirstName =
			getInsuredFirstName();

		String insuredFirstName =
			quotationExtraTameeniInfoCacheModel.insuredFirstName;

		if ((insuredFirstName != null) && (insuredFirstName.length() == 0)) {
			quotationExtraTameeniInfoCacheModel.insuredFirstName = null;
		}

		quotationExtraTameeniInfoCacheModel.insuredMiddleName =
			getInsuredMiddleName();

		String insuredMiddleName =
			quotationExtraTameeniInfoCacheModel.insuredMiddleName;

		if ((insuredMiddleName != null) && (insuredMiddleName.length() == 0)) {
			quotationExtraTameeniInfoCacheModel.insuredMiddleName = null;
		}

		quotationExtraTameeniInfoCacheModel.insuredLastName =
			getInsuredLastName();

		String insuredLastName =
			quotationExtraTameeniInfoCacheModel.insuredLastName;

		if ((insuredLastName != null) && (insuredLastName.length() == 0)) {
			quotationExtraTameeniInfoCacheModel.insuredLastName = null;
		}

		quotationExtraTameeniInfoCacheModel.isDriverDisabled =
			isIsDriverDisabled();

		quotationExtraTameeniInfoCacheModel.vehicleMakeCodeTameeni =
			getVehicleMakeCodeTameeni();

		quotationExtraTameeniInfoCacheModel.coverAgeLimit = getCoverAgeLimit();

		quotationExtraTameeniInfoCacheModel.insuredNameLang =
			getInsuredNameLang();

		String insuredNameLang =
			quotationExtraTameeniInfoCacheModel.insuredNameLang;

		if ((insuredNameLang != null) && (insuredNameLang.length() == 0)) {
			quotationExtraTameeniInfoCacheModel.insuredNameLang = null;
		}

		quotationExtraTameeniInfoCacheModel.policyTitleId = getPolicyTitleId();

		String policyTitleId =
			quotationExtraTameeniInfoCacheModel.policyTitleId;

		if ((policyTitleId != null) && (policyTitleId.length() == 0)) {
			quotationExtraTameeniInfoCacheModel.policyTitleId = null;
		}

		quotationExtraTameeniInfoCacheModel.isRenewal = isIsRenewal();

		return quotationExtraTameeniInfoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<QuotationExtraTameeniInfo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<QuotationExtraTameeniInfo, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<QuotationExtraTameeniInfo, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((QuotationExtraTameeniInfo)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<QuotationExtraTameeniInfo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<QuotationExtraTameeniInfo, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<QuotationExtraTameeniInfo, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((QuotationExtraTameeniInfo)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, QuotationExtraTameeniInfo>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _quotationId;
	private String _insuredFirstName;
	private String _insuredMiddleName;
	private String _insuredLastName;
	private boolean _isDriverDisabled;
	private long _vehicleMakeCodeTameeni;
	private long _coverAgeLimit;
	private String _insuredNameLang;
	private String _policyTitleId;
	private boolean _isRenewal;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<QuotationExtraTameeniInfo, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((QuotationExtraTameeniInfo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("QUOTATION_ID", _quotationId);
		_columnOriginalValues.put("INSURED_FIRST_NAME", _insuredFirstName);
		_columnOriginalValues.put("INSURED_MIDDLE_NAME", _insuredMiddleName);
		_columnOriginalValues.put("INSURED_LAST_NAME", _insuredLastName);
		_columnOriginalValues.put("IS_DRIVER_DISABLED", _isDriverDisabled);
		_columnOriginalValues.put(
			"VEHICLE_MAKE_CODE_TAMEENI", _vehicleMakeCodeTameeni);
		_columnOriginalValues.put("COVER_AGE_LIMIT", _coverAgeLimit);
		_columnOriginalValues.put("INSURED_NAME_LANG", _insuredNameLang);
		_columnOriginalValues.put("POLICY_TITLE_ID", _policyTitleId);
		_columnOriginalValues.put("IS_RENEWAL", _isRenewal);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("QUOTATION_ID", "quotationId");
		attributeNames.put("INSURED_FIRST_NAME", "insuredFirstName");
		attributeNames.put("INSURED_MIDDLE_NAME", "insuredMiddleName");
		attributeNames.put("INSURED_LAST_NAME", "insuredLastName");
		attributeNames.put("IS_DRIVER_DISABLED", "isDriverDisabled");
		attributeNames.put(
			"VEHICLE_MAKE_CODE_TAMEENI", "vehicleMakeCodeTameeni");
		attributeNames.put("COVER_AGE_LIMIT", "coverAgeLimit");
		attributeNames.put("INSURED_NAME_LANG", "insuredNameLang");
		attributeNames.put("POLICY_TITLE_ID", "policyTitleId");
		attributeNames.put("IS_RENEWAL", "isRenewal");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("QUOTATION_ID", 1L);

		columnBitmasks.put("INSURED_FIRST_NAME", 2L);

		columnBitmasks.put("INSURED_MIDDLE_NAME", 4L);

		columnBitmasks.put("INSURED_LAST_NAME", 8L);

		columnBitmasks.put("IS_DRIVER_DISABLED", 16L);

		columnBitmasks.put("VEHICLE_MAKE_CODE_TAMEENI", 32L);

		columnBitmasks.put("COVER_AGE_LIMIT", 64L);

		columnBitmasks.put("INSURED_NAME_LANG", 128L);

		columnBitmasks.put("POLICY_TITLE_ID", 256L);

		columnBitmasks.put("IS_RENEWAL", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private QuotationExtraTameeniInfo _escapedModel;

}