/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.atmc.acl.db.model.impl;

import com.ejada.atmc.acl.db.model.ServiceRequestMessages;
import com.ejada.atmc.acl.db.model.ServiceRequestMessagesModel;
import com.ejada.atmc.acl.db.model.ServiceRequestMessagesSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ServiceRequestMessages service. Represents a row in the &quot;SERVICE_REQUEST_MESSAGES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ServiceRequestMessagesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ServiceRequestMessagesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ServiceRequestMessagesImpl
 * @generated
 */
@JSON(strict = true)
public class ServiceRequestMessagesModelImpl
	extends BaseModelImpl<ServiceRequestMessages>
	implements ServiceRequestMessagesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a service request messages model instance should use the <code>ServiceRequestMessages</code> interface instead.
	 */
	public static final String TABLE_NAME = "SERVICE_REQUEST_MESSAGES";

	public static final Object[][] TABLE_COLUMNS = {
		{"MESSAGE_ID", Types.BIGINT}, {"REFERENCE_NO", Types.VARCHAR},
		{"USER_ID", Types.VARCHAR}, {"USER_NAME", Types.VARCHAR},
		{"USER_TYPE", Types.VARCHAR}, {"USER_MESSAGE", Types.VARCHAR},
		{"TIME_STAMP", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("MESSAGE_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("REFERENCE_NO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("USER_ID", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("USER_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("USER_TYPE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("USER_MESSAGE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TIME_STAMP", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SERVICE_REQUEST_MESSAGES (MESSAGE_ID LONG not null primary key,REFERENCE_NO VARCHAR(75) null,USER_ID VARCHAR(75) null,USER_NAME VARCHAR(75) null,USER_TYPE VARCHAR(75) null,USER_MESSAGE VARCHAR(75) null,TIME_STAMP DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table SERVICE_REQUEST_MESSAGES";

	public static final String ORDER_BY_JPQL =
		" ORDER BY serviceRequestMessages.TIME_STAMP ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SERVICE_REQUEST_MESSAGES.TIME_STAMP ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long REFERENCE_NO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long TIME_STAMP_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ServiceRequestMessages toModel(
		ServiceRequestMessagesSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		ServiceRequestMessages model = new ServiceRequestMessagesImpl();

		model.setMESSAGE_ID(soapModel.getMESSAGE_ID());
		model.setREFERENCE_NO(soapModel.getREFERENCE_NO());
		model.setUSER_ID(soapModel.getUSER_ID());
		model.setUSER_NAME(soapModel.getUSER_NAME());
		model.setUSER_TYPE(soapModel.getUSER_TYPE());
		model.setUSER_MESSAGE(soapModel.getUSER_MESSAGE());
		model.setTIME_STAMP(soapModel.getTIME_STAMP());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ServiceRequestMessages> toModels(
		ServiceRequestMessagesSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ServiceRequestMessages> models =
			new ArrayList<ServiceRequestMessages>(soapModels.length);

		for (ServiceRequestMessagesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ServiceRequestMessagesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _MESSAGE_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMESSAGE_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _MESSAGE_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ServiceRequestMessages.class;
	}

	@Override
	public String getModelClassName() {
		return ServiceRequestMessages.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ServiceRequestMessages, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ServiceRequestMessages, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ServiceRequestMessages, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ServiceRequestMessages)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ServiceRequestMessages, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ServiceRequestMessages, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ServiceRequestMessages)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ServiceRequestMessages, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ServiceRequestMessages, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ServiceRequestMessages>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ServiceRequestMessages.class.getClassLoader(),
			ServiceRequestMessages.class, ModelWrapper.class);

		try {
			Constructor<ServiceRequestMessages> constructor =
				(Constructor<ServiceRequestMessages>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ServiceRequestMessages, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ServiceRequestMessages, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ServiceRequestMessages, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ServiceRequestMessages, Object>>();
		Map<String, BiConsumer<ServiceRequestMessages, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ServiceRequestMessages, ?>>();

		attributeGetterFunctions.put(
			"MESSAGE_ID", ServiceRequestMessages::getMESSAGE_ID);
		attributeSetterBiConsumers.put(
			"MESSAGE_ID",
			(BiConsumer<ServiceRequestMessages, Long>)
				ServiceRequestMessages::setMESSAGE_ID);
		attributeGetterFunctions.put(
			"REFERENCE_NO", ServiceRequestMessages::getREFERENCE_NO);
		attributeSetterBiConsumers.put(
			"REFERENCE_NO",
			(BiConsumer<ServiceRequestMessages, String>)
				ServiceRequestMessages::setREFERENCE_NO);
		attributeGetterFunctions.put(
			"USER_ID", ServiceRequestMessages::getUSER_ID);
		attributeSetterBiConsumers.put(
			"USER_ID",
			(BiConsumer<ServiceRequestMessages, String>)
				ServiceRequestMessages::setUSER_ID);
		attributeGetterFunctions.put(
			"USER_NAME", ServiceRequestMessages::getUSER_NAME);
		attributeSetterBiConsumers.put(
			"USER_NAME",
			(BiConsumer<ServiceRequestMessages, String>)
				ServiceRequestMessages::setUSER_NAME);
		attributeGetterFunctions.put(
			"USER_TYPE", ServiceRequestMessages::getUSER_TYPE);
		attributeSetterBiConsumers.put(
			"USER_TYPE",
			(BiConsumer<ServiceRequestMessages, String>)
				ServiceRequestMessages::setUSER_TYPE);
		attributeGetterFunctions.put(
			"USER_MESSAGE", ServiceRequestMessages::getUSER_MESSAGE);
		attributeSetterBiConsumers.put(
			"USER_MESSAGE",
			(BiConsumer<ServiceRequestMessages, String>)
				ServiceRequestMessages::setUSER_MESSAGE);
		attributeGetterFunctions.put(
			"TIME_STAMP", ServiceRequestMessages::getTIME_STAMP);
		attributeSetterBiConsumers.put(
			"TIME_STAMP",
			(BiConsumer<ServiceRequestMessages, Date>)
				ServiceRequestMessages::setTIME_STAMP);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMESSAGE_ID() {
		return _MESSAGE_ID;
	}

	@Override
	public void setMESSAGE_ID(long MESSAGE_ID) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_MESSAGE_ID = MESSAGE_ID;
	}

	@JSON
	@Override
	public String getREFERENCE_NO() {
		if (_REFERENCE_NO == null) {
			return "";
		}
		else {
			return _REFERENCE_NO;
		}
	}

	@Override
	public void setREFERENCE_NO(String REFERENCE_NO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_REFERENCE_NO = REFERENCE_NO;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalREFERENCE_NO() {
		return getColumnOriginalValue("REFERENCE_NO");
	}

	@JSON
	@Override
	public String getUSER_ID() {
		if (_USER_ID == null) {
			return "";
		}
		else {
			return _USER_ID;
		}
	}

	@Override
	public void setUSER_ID(String USER_ID) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_USER_ID = USER_ID;
	}

	@JSON
	@Override
	public String getUSER_NAME() {
		if (_USER_NAME == null) {
			return "";
		}
		else {
			return _USER_NAME;
		}
	}

	@Override
	public void setUSER_NAME(String USER_NAME) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_USER_NAME = USER_NAME;
	}

	@JSON
	@Override
	public String getUSER_TYPE() {
		if (_USER_TYPE == null) {
			return "";
		}
		else {
			return _USER_TYPE;
		}
	}

	@Override
	public void setUSER_TYPE(String USER_TYPE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_USER_TYPE = USER_TYPE;
	}

	@JSON
	@Override
	public String getUSER_MESSAGE() {
		if (_USER_MESSAGE == null) {
			return "";
		}
		else {
			return _USER_MESSAGE;
		}
	}

	@Override
	public void setUSER_MESSAGE(String USER_MESSAGE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_USER_MESSAGE = USER_MESSAGE;
	}

	@JSON
	@Override
	public Date getTIME_STAMP() {
		return _TIME_STAMP;
	}

	@Override
	public void setTIME_STAMP(Date TIME_STAMP) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TIME_STAMP = TIME_STAMP;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ServiceRequestMessages.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ServiceRequestMessages toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ServiceRequestMessages>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ServiceRequestMessagesImpl serviceRequestMessagesImpl =
			new ServiceRequestMessagesImpl();

		serviceRequestMessagesImpl.setMESSAGE_ID(getMESSAGE_ID());
		serviceRequestMessagesImpl.setREFERENCE_NO(getREFERENCE_NO());
		serviceRequestMessagesImpl.setUSER_ID(getUSER_ID());
		serviceRequestMessagesImpl.setUSER_NAME(getUSER_NAME());
		serviceRequestMessagesImpl.setUSER_TYPE(getUSER_TYPE());
		serviceRequestMessagesImpl.setUSER_MESSAGE(getUSER_MESSAGE());
		serviceRequestMessagesImpl.setTIME_STAMP(getTIME_STAMP());

		serviceRequestMessagesImpl.resetOriginalValues();

		return serviceRequestMessagesImpl;
	}

	@Override
	public int compareTo(ServiceRequestMessages serviceRequestMessages) {
		int value = 0;

		value = DateUtil.compareTo(
			getTIME_STAMP(), serviceRequestMessages.getTIME_STAMP());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ServiceRequestMessages)) {
			return false;
		}

		ServiceRequestMessages serviceRequestMessages =
			(ServiceRequestMessages)object;

		long primaryKey = serviceRequestMessages.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ServiceRequestMessages> toCacheModel() {
		ServiceRequestMessagesCacheModel serviceRequestMessagesCacheModel =
			new ServiceRequestMessagesCacheModel();

		serviceRequestMessagesCacheModel.MESSAGE_ID = getMESSAGE_ID();

		serviceRequestMessagesCacheModel.REFERENCE_NO = getREFERENCE_NO();

		String REFERENCE_NO = serviceRequestMessagesCacheModel.REFERENCE_NO;

		if ((REFERENCE_NO != null) && (REFERENCE_NO.length() == 0)) {
			serviceRequestMessagesCacheModel.REFERENCE_NO = null;
		}

		serviceRequestMessagesCacheModel.USER_ID = getUSER_ID();

		String USER_ID = serviceRequestMessagesCacheModel.USER_ID;

		if ((USER_ID != null) && (USER_ID.length() == 0)) {
			serviceRequestMessagesCacheModel.USER_ID = null;
		}

		serviceRequestMessagesCacheModel.USER_NAME = getUSER_NAME();

		String USER_NAME = serviceRequestMessagesCacheModel.USER_NAME;

		if ((USER_NAME != null) && (USER_NAME.length() == 0)) {
			serviceRequestMessagesCacheModel.USER_NAME = null;
		}

		serviceRequestMessagesCacheModel.USER_TYPE = getUSER_TYPE();

		String USER_TYPE = serviceRequestMessagesCacheModel.USER_TYPE;

		if ((USER_TYPE != null) && (USER_TYPE.length() == 0)) {
			serviceRequestMessagesCacheModel.USER_TYPE = null;
		}

		serviceRequestMessagesCacheModel.USER_MESSAGE = getUSER_MESSAGE();

		String USER_MESSAGE = serviceRequestMessagesCacheModel.USER_MESSAGE;

		if ((USER_MESSAGE != null) && (USER_MESSAGE.length() == 0)) {
			serviceRequestMessagesCacheModel.USER_MESSAGE = null;
		}

		Date TIME_STAMP = getTIME_STAMP();

		if (TIME_STAMP != null) {
			serviceRequestMessagesCacheModel.TIME_STAMP = TIME_STAMP.getTime();
		}
		else {
			serviceRequestMessagesCacheModel.TIME_STAMP = Long.MIN_VALUE;
		}

		return serviceRequestMessagesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ServiceRequestMessages, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ServiceRequestMessages, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ServiceRequestMessages, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((ServiceRequestMessages)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ServiceRequestMessages, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ServiceRequestMessages, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ServiceRequestMessages, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((ServiceRequestMessages)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ServiceRequestMessages>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _MESSAGE_ID;

	private String _REFERENCE_NO;

	private String _USER_ID;

	private String _USER_NAME;

	private String _USER_TYPE;

	private String _USER_MESSAGE;

	private Date _TIME_STAMP;

	public <T> T getColumnValue(String columnName) {
		Function<ServiceRequestMessages, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ServiceRequestMessages)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("MESSAGE_ID", _MESSAGE_ID);
		_columnOriginalValues.put("REFERENCE_NO", _REFERENCE_NO);
		_columnOriginalValues.put("USER_ID", _USER_ID);
		_columnOriginalValues.put("USER_NAME", _USER_NAME);
		_columnOriginalValues.put("USER_TYPE", _USER_TYPE);
		_columnOriginalValues.put("USER_MESSAGE", _USER_MESSAGE);
		_columnOriginalValues.put("TIME_STAMP", _TIME_STAMP);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("MESSAGE_ID", 1L);

		columnBitmasks.put("REFERENCE_NO", 2L);

		columnBitmasks.put("USER_ID", 4L);

		columnBitmasks.put("USER_NAME", 8L);

		columnBitmasks.put("USER_TYPE", 16L);

		columnBitmasks.put("USER_MESSAGE", 32L);

		columnBitmasks.put("TIME_STAMP", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ServiceRequestMessages _escapedModel;

}